diffkemp/diffkemp

- tests/unit_tests/build_llvm_test.py
- tests/unit_tests/kernel_source_test.py
Added some unit tests for build_llvm. Added tests for kernel_source. Moved test for get_sources_with_params to tests for kernel_source.
> Added unit tests.

- diffkemp/diffkemp.py
- diffkemp/diffsysctl.py
- diffkemp/llvm_ir/function_collector.py
- diffkemp/llvm_ir/kernel_module.py
- diffkemp/llvm_ir/llvm_sysctl_module.py
- diffkemp/semdiff/function_diff.py
- diffkemp/semdiff/module_diff.py
- tests/regression/diffkemp/diffkemp_test.py
Includes an improvement of modules_diff - now it can use a parameter with attached indices.
> diffsysctl: Finding data variable by GEPs

- diffkemp/diffkabi.py
> diffkabi: Fixed an issue when diffkabi crashed because of trying to clean modules when the variables were not assigned.

- diffkemp/semdiff/function_diff.py
- diffkemp/semdiff/result.py
- diffkemp/simpll/Output.cpp
- diffkemp/simpll/simpll.py
- diffkemp/syndiff/function_syntax_diff.py
- docker/diffkemp-devel/Dockerfile
- tests/unit_tests/function_syntax_diff_test.py
Implements function extraction from C source files. The functions are put into separate files, which are then compared using regular diff utility. The output is then modified to be as close to the original output (line numbers are fixed and the function header is added).
> Remove custom diff

- diffkemp/diffkabi.py
Function whose diff does not contain the specified regular
expression is treated as equal.
> Added option to filter diffs by regex to diffkabi.

- .travis.yml
- bin/diffkabi
- bin/diffkemp
- bin/diffsysctl
- diffkemp/diffkabi.py
- diffkemp/diffkemp.py
- diffkemp/diffsysctl.py
- diffkemp/llvm_ir/build_llvm.py
- diffkemp/llvm_ir/function_collector.py
- diffkemp/llvm_ir/kernel_module.py
- diffkemp/llvm_ir/kernel_source.py
- diffkemp/llvm_ir/llvm_sysctl_module.py
- diffkemp/semdiff/function_coupling.py
- diffkemp/semdiff/function_diff.py
- diffkemp/semdiff/module_diff.py
- diffkemp/semdiff/result.py
- diffkemp/simpll/simpll.py
- diffkemp/syndiff/function_syntax_diff.py
- docker/diffkemp-devel/Dockerfile
- requirements.txt
- setup.py
- tests/regression/diffkabi/diffkabi_test.py
- tests/regression/diffkemp/diffkemp_test.py
- tests/regression/diffsysctl/diffsysctl_test.py
- tests/unit_tests/build_llvm_test.py
- tests/unit_tests/kernel_module_test.py
- tests/unit_tests/llvm_sysctl_module_test.py
> Migration to Python 3.

- .travis.yml
- CMakeLists.txt
- README.md
- diffkemp/llvm_ir/kernel_module.py
- diffkemp/llvm_ir/kernel_source.py
- diffkemp/llvm_ir/llvm_sysctl_module.py
- diffkemp/simpll/DifferentialFunctionComparator.cpp
- diffkemp/simpll/FunctionComparator.cpp
- diffkemp/simpll/FunctionComparator.h
- diffkemp/simpll/Transforms.cpp
- diffkemp/simpll/passes/RemoveUnusedReturnValuesPass.cpp
- diffkemp/simpll/passes/UnifyMemcpyPass.cpp
- diffkemp/simpll/passes/VarDependencySlicer.cpp
- diffkemp/simpll/passes/VarDependencySlicer.h
- docker/diffkemp-devel/Dockerfile
- tests/unit_tests/kernel_module_test.py
For now, LLVM 8 will be the main supported LLVM version.
Support for older versions will come soon.
> Migrate to LLVM 8.

- diffkemp/semdiff/function_diff.py
- diffkemp/semdiff/result.py
In addtional to statistics about compared symbols, print
statistics about unique differences, too.
> Extend statistics reporting.

- diffkemp/simpll/SourceCodeUtils.cpp
This saves the macro name to MacroElement map for each module to another
map when it is generated and reuses it the next time SimpLL looks for
macros in the same module.
> SimpLL: Cache macro map.

- diffkemp/simpll/DifferentialFunctionComparator.cpp
- diffkemp/simpll/passes/FieldAccessFunctionGenerator.cpp
> Bugfix in FieldAccessFunctionGenerator and DifferentialFunctionComparator.

- diffkemp/simpll/passes/CalledFunctionsAnalysis.cpp
- diffkemp/simpll/passes/CalledFunctionsAnalysis.h
> SimpLL: Preprocess functions in global variables.

- .gitignore
- diffkemp/function_list.py
- diffkemp/simpll/CMakeLists.txt
- diffkemp/simpll/simpll.py
- rpm/diffkemp.spec
- setup.py
- tests/regression/functions_test.py
- tests/regression/modules_test.py
- tests/regression/sysctls_test.py
This includes several changes, see individual commit messages.
> Prepare everything to build RPM package

- .travis.yml
- diffkemp/simpll/SimpLL.cpp
- diffkemp/simpll/Transforms.cpp
- diffkemp/simpll/llvm-lib/9/FunctionComparator.cpp
- diffkemp/simpll/llvm-lib/9/FunctionComparator.h
- docker/diffkemp-devel/Dockerfile
Adds support for LLVM 9 and removes the unused postprocess phase from SimpLL.
> Add support for LLVM 9.

- diffkemp/diffkemp.py
- diffkemp/semdiff/function_diff.py
- diffkemp/semdiff/result.py
- tests/regression/test_specs/rhel-73-74.yaml
- tests/regression/test_specs/rhel-74-75-cfo.yaml
- tests/regression/test_specs/rhel-74-75.yaml
- tests/regression/test_specs/rhel-75-76-cfo.yaml
- tests/regression/test_specs/rhel-75-76.yaml
- tests/regression/test_specs/upstream-3.10-4.11.yaml
> Merge occurences of EQUAL_SYNTAX with EQUAL

- .github/workflows/ci.yml
- CMakeLists.txt
- README.md
- diffkemp/simpll/DebugInfo.cpp
- diffkemp/simpll/Utils.cpp
- diffkemp/simpll/Utils.h
- diffkemp/simpll/llvm-lib/12/FunctionComparator.cpp
- diffkemp/simpll/llvm-lib/12/FunctionComparator.h
- diffkemp/simpll/passes/VarDependencySlicer.cpp
- diffkemp/simpll/passes/VarDependencySlicer.h
- docker/diffkemp-devel/Dockerfile
Several minor updates:
- remove CMake warning
- support LLVM 12
- fix Dockerfile
- update README
Feel free to suggest more that could be done in this PR.
> Various cleanups and LLVM 12 support

- diffkemp/simpll/CMakeLists.txt
> remove -fvisibility=hidden from simpll build

- diffkemp/simpll/passes/SimplifyKernelFunctionCallsPass.cpp
The first parameter of these calls is `__COUNTER__` whose value is not relevant (its purpose is to make the calls unique to prevent GCC merging them) so we remove it in `SimplifyKernelFunctionCallsPass`.
This also slightly refactors the pass by reducing some horizontal whitespace.
> Handle kernel's .discard.(un)reachable asm calls

- diffkemp/llvm_ir/kernel_llvm_source_builder.py
When merged, this PR resolves #212.
I've enclosed the call to _cscope_ into a `try .. except` block, removing _scope.files_ when _scope_ database build fails.
This should also cover the case when _cscope_ is interrupted since the same exception will be raised by _subprocess_.
Is it a viable solution?
> [WIP] Delete cscope.files when cscope database build fails

- diffkemp/cli.py
- diffkemp/diffkemp.py
- diffkemp/simpll/DebugInfo.cpp
- diffkemp/simpll/DebugInfo.h
- diffkemp/simpll/DifferentialFunctionComparator.cpp
- diffkemp/simpll/DifferentialFunctionComparator.h
- diffkemp/simpll/Logger.cpp
- diffkemp/simpll/Logger.h
- diffkemp/simpll/ModuleAnalysis.cpp
- diffkemp/simpll/ModuleComparator.cpp
- diffkemp/simpll/PatternComparator.cpp
- diffkemp/simpll/PatternSet.cpp
- diffkemp/simpll/SourceCodeUtils.cpp
- diffkemp/simpll/passes/ControlFlowSlicer.cpp
- diffkemp/simpll/passes/FunctionAbstractionsGenerator.cpp
- diffkemp/simpll/passes/RemoveUnusedReturnValuesPass.cpp
- diffkemp/simpll/passes/SeparateCallsToBitcastPass.cpp
- diffkemp/simpll/passes/VarDependencySlicer.cpp
Implements logger, simplifying the way debug logging is done and adding conditional logging to comparisons in DifferentialFunctionComparator. For this kind of logging, the logger takes into the account the hierarchy of comparisons, logging only messages regarding comparisons that eventually lead to failure of instruction comparisons or those that are forced to log using higher debug level option.
> Comparison logger

- README.md
- diffkemp/cli.py
- diffkemp/diffkemp.py
- diffkemp/llvm_ir/single_c_builder.py
- diffkemp/llvm_ir/wrapper_build_finder.py
- diffkemp/utils.py
This PR extends `diffkemp build` to be able to make snapshots from a single C file.
> Add creating snapshots for a single C file

- README.md
- diffkemp/simpll/Logger.cpp
More details in the commits. As for the README change, there doesn't seem to be a way to build without tests right now unless I am missing something.
Fixes: #281
> Fix build & build instructions

- diffkemp/simpll/Config.h
> Initialize ExtendedStat in tests

- diffkemp/output.py
- diffkemp/simpll/DifferentialFunctionComparator.cpp
- diffkemp/simpll/DifferentialFunctionComparator.h
- diffkemp/simpll/passes/CalledFunctionsAnalysis.cpp
- diffkemp/simpll/passes/CalledFunctionsAnalysis.h
This PR fixes 3 bugs I encountered when analyzing cryptographic libraries. For details, see commit messages.
> Various bug fixes

- .github/workflows/ci.yml
- bin/diffkemp
- diffkemp/cli.py
- diffkemp/diffkemp.py
Cherry-picking this commit from #315 to make building with nix work for now, since LLVM17 support maybe a bit more complicated
> Fix circular import

- .github/workflows/ci.yml
- tests/testing_projects/.gitignore
- tests/testing_projects/README.md
- tests/testing_projects/make_based/Makefile
- tests/testing_projects/make_based/file.c
- tests/unit_tests/build_test.py
As discussed in #311  this PR adds tests for the build command and also adds compiling of cc_wrapper with RPython to CI, to check if the compilation is successful. This PR should be merged before #311.
> Build tests

- .github/workflows/ci.yml
- diffkemp/semdiff/custom_pattern_config.py
- diffkemp/simpll/DifferentialFunctionComparator.cpp
- diffkemp/simpll/DifferentialFunctionComparator.h
- diffkemp/simpll/InstPatternComparator.cpp
- diffkemp/simpll/InstPatternComparator.h
- diffkemp/simpll/llvm-lib/17/FunctionComparator.cpp
- diffkemp/simpll/llvm-lib/17/FunctionComparator.h
- flake.lock
- flake.nix
- tests/unit_tests/simpll/DifferentialFunctionComparatorTest.cpp
- added support for LLVM 17 + adjusted nix config
> Add support for LLVM17

- CMakeLists.txt
- flake.nix
- rpm/diffkemp.spec
- setup.py
Changelog:
- Allow creating snapshots from a single C source file
- Add extended analysis statistics
- New pattern for matching reordered binary operations
- New pattern for variable grouping
- Nix flakes support for building and development
- Unification of applied optimizations for various build commands
- Fix comparison of PHI nodes and union types
> Release 0.6.0

- diffkemp/semdiff/result.py
- diffkemp/utils.py
- tests/unit_tests/result_test.py
Second part of commits from https://github.com/diffkemp/diffkemp/pull/314 .
This PR adds:
- method for extracting macro definitions from the call stacks (it is possible to extract information about definitions for all macros except the differing macros for which is the definition extracted in [#333](https://github.com/diffkemp/diffkemp/pull/333) PR)
- update of `get_end_line` function to be possible to use it also for finding line where macro ends.
> Extraction of macro definitions from callstacks

- flake.nix
Added flake8 to the Nix Python packages to enable checking of coding style inside the Nix development shell.
> Add flake8 to nix dev shell

- CMakeLists.txt
- flake.nix
- rpm/diffkemp.spec
- setup.py
Changelog:
- Various bug fixes
- Run GVN pass after function inlining
- Release for TOSEM 2024 publication
> Release 0.6.1

- diffkemp/simpll/Utils.cpp
- tests/unit_tests/simpll/DifferentialFunctionComparatorTest.cpp
This PR fixes #363 -- not handling memset of structures with different sizes (e.g. because of different struct alignment caused by swapped struct fields) when the structure has typedef and opaque pointers are used (more info in commit message).
> Make `cmpMemset` work for typedefed structs

- .flake8
- .github/workflows/code-style.yml
- tests/unit_tests/caching_test.py
Creates .flake8 config to centralize code style settings.
> Create flake8 config file. Fixes #392

- .github/workflows/builds.yml
- .github/workflows/ci.yml
- CMakeLists.txt
- bin/diffkemp
- diffkemp/building/build_c_project.py
- diffkemp/diffkemp.in
- diffkemp/llvm_ir/llvm_module.py
- diffkemp/semdiff/caching.py
- diffkemp/simpll/CMakeLists.txt
- diffkemp/simpll/simpll_build.py
- diffkemp/simpll/simpll_lib.py
- diffkemp/snapshot.py
- docs/development.md
- docs/installation.md
- flake.nix
- pyproject.toml
- requirements.txt
- setup.py
- tests/unit_tests/result_test.py
- tests/unit_tests/run_pytest_tests.py.in
- tests/unit_tests/simpll/CMakeLists.txt
This pull requests addresses issue #338 and updates our python infrastructure.
> Modernize python builds

- diffkemp/semdiff/result.py
This fixes an issue mentioned in #413. Tested on kernels from `examples`.
> Bug fix: result.graph updating to None
