diffkemp/simpll/passes/RemoveUnusedReturnValuesPass.cpp
Checking whether the function has a body using `GlobalValue::LinkageTypes::ExternalLinkage` is unreliable; for example when run on simple programs it replaces the return type of the main function, making it incomparable by `DifferentialFunctionComparator`, which compares the deleted old function instead.
This bug didn't appear until the `callsTransitively` check was replaced by a function list, because the old method excluded the main function.
The proposed fix is to actually check the number of basic blocks in the function, and if it's not zero, then skip the function.
=> SimpLL: RemoveUnusedReturnValuesPass: Skip all functions without a body.

diffkemp/simpll/Transforms.cpp, diffkemp/simpll/passes/RemoveUnusedReturnValuesPass.cpp, diffkemp/simpll/passes/RemoveUnusedReturnValuesPass.h
The optimization of RemoveUnunsedReturnValuesPass, checking whether the function is void in the other module, in case it is not (or does not exist in the other module), skip it.
=> SimpLL: RemoveUnunsedReturnValuesPass: Replace only functions that are of void type in the other module.

diffkemp/simpll/DebugInfo.cpp, diffkemp/simpll/DebugInfo.h, diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/DifferentialFunctionComparator.h, diffkemp/simpll/ModuleComparator.cpp, diffkemp/simpll/ModuleComparator.h, diffkemp/simpll/Transforms.cpp
It should work (it works in the "ramoops" test case in the spreadsheet), but there are still problems (in some cases) with LLVM `DebugInfoFinder` class, which is not able to find all composite types.
=> SimpLL: Compare struct GEPs by member names using debug information.

tests/regression/test_specs/wm97xx_ts.yaml
Functions wm9705_poll_touch and wm9705_acc_enable are now declared equal by SimpLL, so they no longer timeout. This can be used as a test whether the better cmpGEPs is working in this case.
(This is the case on line 15 in the spreadsheet.)
=> Added test for better cmpGEPs in SimpLL.

diffkemp/simpll/DebugInfo.cpp, diffkemp/simpll/DebugInfo.h, tests/regression/kernel_modules/b2c2-flexcop/b2c2-flexcop_new.c, tests/regression/kernel_modules/b2c2-flexcop/b2c2-flexcop_old.c, tests/regression/test_specs/b2c2-flexcop.yaml
Concurrent iteration through equivalent code in the other module is used to get the corresponding GEP instruction, from which the corresponding StructType is extracted. When the iteration fails at any level (for example by reaching the end prematurely), it is stopped and the old method of finding the corresponding StructType (searching for the type name in the other module) is used.
=> SimpLL: Updated DebugInfo to assign correct StructTypes as the keys of StructFieldNames in cases where their names differ.

diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/DifferentialFunctionComparator.h
structure types by names instead of comparing allocated memory size by
the raw value.
(Currently ignores kzalloc flags.)
Note: I don't have a test case yet, because all cases in the spreadsheet have another difference beside the allocation function inaccuracy.
=> SimpLL: Fixed comparing kzalloc instructions - now comparing

diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/DifferentialFunctionComparator.h
cmpOperations to a new function called cmpAllocs.
=> SimpLL: Moved the comparison of allocation functions from

diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/DifferentialFunctionComparator.h, diffkemp/simpll/ModuleComparator.cpp, diffkemp/simpll/ModuleComparator.h, diffkemp/simpll/Transforms.cpp
the switch -control-flow is active.
=> SimpLL: Ignore additional null argument in function calls only if

.gitignore, diffkemp/llvm_ir/llvm_sysctl_module.py, tests/regression/diffsysctl/diffsysctl_test.py, tests/regression/diffsysctl/test_specs/rhel-75-76.yaml, tests/unit_tests/build_llvm_test.py, tests/unit_tests/kernel_source_test.py, tests/unit_tests/llvm_sysctl_module_test.py
Added regression test support for diffsysctl and unit tests for the LlvmSysctlModule class.
Also fixed a bug in LlvmSysctlModule that caused processing GEPs without bitcats to lead to a type conversion error in LLVM (the function get_data attempted to get the const opcode of a non-ConstantExpr value).
=> diffsysctl tests

diffkemp/simpll/DifferentialFunctionComparator.cpp
the allocated memory size is compared equal by cmpValues.
=> Improved cmpAllocs - now compares alloc functions as equal when

diffkemp/llvm_ir/kernel_source.py, diffkemp/semdiff/function_diff.py, tests/regression/diffkabi/test_specs/rhel-75-76.yaml
=> kernel_source: Fixed two special cases when cscope fails because of the usage of a macro

docker/diffkemp/run-diffkabi.sh
Modified run-diffkabi.sh to include the full name of the Docker container in order for it to be able to download the container from Docker Hub in case it is not present on the machine.
=> Fixed run-diffkabi.sh to be able to download the container from Docker Hub

diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/DifferentialFunctionComparator.h, tests/regression/diffkabi/test_specs/rhel-75-76.yaml
This fixes one of the problems with empty diff.
=> SimpLL: Compare array types with the same element type as equal when comparing the control flow only

diffkemp/simpll/Transforms.cpp, diffkemp/simpll/passes/ReduceFunctionMetadataPass.cpp, diffkemp/simpll/passes/ReduceFunctionMetadataPass.h
This is to fix the function usleep_range comparing as not equal. 
There is another problem with a return value when comparing the same function, which could be solved by extending the RemoveUnusedReturnValuesPass to all functions. (I didn't include that here because I'm not currently sure whether this causes any problems or not, that yet has to be tested.)
=> SimpLL: Remove function sections when comparing the control flow only.

diffkemp/simpll/Transforms.cpp, diffkemp/simpll/passes/RemoveUnusedReturnValuesPass.cpp, diffkemp/simpll/passes/SimplifyKernelGlobalsPass.cpp
perform the same thing on the main function.
Also added code to remove kernel symbol table structures, because
they are not needed for the comparison and are interfering with
the aforementioned pass.
Fixes #33
=> SimpLL: Modified RemoveUnusedReturnValuesPass to be able to

diffkemp/simpll/Utils.cpp, diffkemp/simpll/Utils.h, diffkemp/simpll/passes/RemoveUnusedReturnValuesPass.cpp
not remove empty attribute sets from call and invoke instructions
and didn't copy debug information.
Fixes #33
=> SimpLL: Fixed a bug in RemoveUnusedReturnValuesPass - the pass did

diffkemp/diffkabi.py, diffkemp/semdiff/function_diff.py, diffkemp/semdiff/result.py, diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/DifferentialFunctionComparator.h, diffkemp/simpll/MacroUtils.cpp, diffkemp/simpll/MacroUtils.h, diffkemp/simpll/ModuleComparator.h, diffkemp/simpll/Output.cpp, diffkemp/simpll/Output.h, diffkemp/simpll/SimpLL.cpp, diffkemp/simpll/Transforms.cpp, diffkemp/simpll/Transforms.h, diffkemp/simpll/Utils.cpp, diffkemp/simpll/Utils.h, diffkemp/simpll/simpll.py
extracting them from the source code, getting a list of used
macros on the corresponding line and comparing them.
Note: this currently does not work in tests, because it can't find the original source file. Also due to a planned change in the communication interface between SimpLL and diffkemp it does not pass the differences to diffkabi yet (they can be seen in the debug output of SimpLL).
=> SimpLL: Added support for detecting differences in macros by

diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/MacroUtils.cpp, diffkemp/simpll/ModuleComparator.cpp
This pull request:
1. Fixes a bug in macro utils that caused the macro finding algorithm to fail when the only thing in a macro's body was another macro.
2. Improves the code that is supposed to extract the line corresponding to a DILocation from the source code to join the adjacent lines when there is an expression longer than one line.
3. Optimizes the call instruction inlining so it does not attempt to inline functions generated by SimpLL itself.
4. Fixes #46
=> Improved macro diff

diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/DifferentialFunctionComparator.h, tests/regression/diffkabi/test_specs/rhel-73-74.yaml
only to constant expressions.
This fixes the function debugfs_create_u32 comparing as non-equal.
=> SimpLL: Extending ignoring of casts when comparing control flow

diffkemp/llvm_ir/build_llvm.py, diffkemp/llvm_ir/kernel_module.py, diffkemp/simpll/CMakeLists.txt, diffkemp/simpll/DebugInfo.cpp, diffkemp/simpll/DifferentialFunctionComparator.h, diffkemp/simpll/DifferentialGlobalNumberState.h, diffkemp/simpll/FunctionComparator.cpp, diffkemp/simpll/FunctionComparator.h, diffkemp/simpll/passes/FunctionAbstractionsGenerator.cpp, diffkemp/simpll/passes/RemoveUnusedReturnValuesPass.cpp, diffkemp/simpll/passes/UnifyMemcpyPass.cpp, diffkemp/simpll/passes/VarDependencySlicer.cpp, diffkemp/simpll/passes/VarDependencySlicer.h, docker/diffkemp-devel/Dockerfile, tests/regression/diffkemp/test_specs/cfg80211.yaml, tests/unit_tests/build_llvm_test.py, tests/unit_tests/kernel_module_test.py
This requires a number of changes/hacks:
- we copy FunctionComparator from LLVM since we need its methods to be virtual
- some of the custom LLVM C API methods are not available now, which mainly causes changes to linking of modules
We currently support LLVM 5.0.2 and link against a single LLVM shared library instead of multiple libraries for each LLVM component. This also required some changes to the SimpLL code.
Limitation: linking whole kernel modules is not possible since both modules contain `init_module` alias and LLVM C API does not allow for deleting global aliases.
=> Remove dependency on custom LLVM

diffkemp/simpll/DifferentialFunctionComparator.cpp
method in LLVM when comparing whether the function to be inlined
was generated by simpll.
This prevents a simplification failure when comparing the function `__alloc_pages_nodemask`.
=> SimpLL: Use the util function getCalledFunction instead of the

.gitignore, .gitmodules, .travis.yml, CMakeLists.txt, README.md, diffkemp/config.py, diffkemp/diffkabi.py, diffkemp/diffkemp.py, diffkemp/diffsysctl.py, diffkemp/semdiff/function_coupling.py, diffkemp/semdiff/function_diff.py, tests/regression/task_spec.py, tests/unit_tests/function_syntax_diff_test.py
Instead of having it as a git submodule, it is possible to download it during CMake by setting `-DBUILD_LLREVE=ON`. From now, LLReve is not run by default (only syntax diff by SimpLL is), it can be turned on by using parameter `--semdiff-tool=llreve`.
=> LLReve is optional as a component

diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/DifferentialFunctionComparator.h, diffkemp/simpll/MacroUtils.cpp, diffkemp/simpll/MacroUtils.h, diffkemp/simpll/ModuleComparator.h, diffkemp/simpll/Output.cpp, diffkemp/simpll/Output.h, diffkemp/simpll/SimpLL.cpp, diffkemp/simpll/Transforms.cpp, diffkemp/simpll/Transforms.h, diffkemp/simpll/passes/FunctionAbstractionsGenerator.cpp, diffkemp/simpll/passes/FunctionAbstractionsGenerator.h
in inline assembly (to be able to show a diff when there is a
differering assembly generated from macros and the difference
cannot be found by following the macros).
This fixes an empty diff when comparing the function `slab_alloc_node` between kernel version 3.10.0-514.el7 and 3.10.0-693.el7.
=> SimpLL: Extend the code for macro differences to cover differences

diffkemp/simpll/ModuleComparator.cpp
=> SimpLL: Do not insert LLVM lifetime calls when inlining.

diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/ModuleComparator.h, diffkemp/simpll/SourceCodeUtils.cpp, diffkemp/simpll/SourceCodeUtils.h, diffkemp/simpll/Transforms.cpp, diffkemp/simpll/Utils.cpp, diffkemp/simpll/Utils.h, diffkemp/simpll/passes/FunctionAbstractionsGenerator.cpp, diffkemp/simpll/passes/FunctionAbstractionsGenerator.h, diffkemp/simpll/passes/StructureSizeAnalysis.cpp, diffkemp/simpll/passes/StructureSizeAnalysis.h
Implements code that can extract arguments that correspond to call instructions operands from C source code for both regular function calls and inline assembly calls.
This is used to avoid differences in C builtin macros like `__LINE__` and `__COUNTER__` being compared as non-equal.
Also implements an analysis of structure type sizes, allowing the comparator to guess whether a change in a call function operand corresponds to a change in structure type size, in which case the values should be treated as equal (the aforementioned C source code utils are used to see whether the exact operand was generated by a `sizeof` or not).
This PR also fixes some bugs preventing the analysis from working correctly.
=> C source call arguments analysis

diffkemp/diffkemp.py, diffkemp/semdiff/function_diff.py, diffkemp/semdiff/result.py, diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/ModuleComparator.cpp, diffkemp/simpll/ModuleComparator.h, diffkemp/simpll/Output.cpp, diffkemp/simpll/SourceCodeUtils.cpp, diffkemp/simpll/SourceCodeUtils.h, diffkemp/simpll/passes/FunctionAbstractionsGenerator.cpp, diffkemp/simpll/passes/ReduceFunctionMetadataPass.cpp, diffkemp/simpll/simpll.py
1. Do not include syntax diff when the parent function is compared as equal (for example when there is a macro found, but the functions calls are inlined and the result is compared as equal).
2. Include an attribute in the output YAML that says whether this function difference is covered by a syntax difference (in other words if there exists a syntax difference with this function as its parent). When an empty diff with this attribute set is encountered in diffkabi, it is excluded from the output. (diffkabi itself cannot distinguish them, because the parent function is not included in the YAML; moreover I think this should be done in SimpLL).
3. Add an option to show a list of functions that are unknown or ended with an error (these are not shown in the diff list, therefore it is useful to …
=> Better syntactic diffs and function abstractions naming

diffkemp/simpll/Output.cpp
The problem was caused by the change of the order of operations in
reportOutput, leading to the variable report.diffFuns not containing all
function differences (and their call stacks) at the point of syntax
difference generation (this order is necessary for the
coveredBySyntaxDiff mechanism to work properly)-
=> SimpLL: Fixed syntax diff call stack appending.

diffkemp/llvm_ir/kernel_module.py, diffkemp/llvm_ir/kernel_source.py
Instead of parsing the LLVM files using LLVM C API bindings, it is
faster to search for functions using regex. A function definition
starts with:
define ... @function_name(...)
=> Optimise finding functions in LLVM IR from Python

diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/DifferentialFunctionComparator.h
There were two problems - the first was the skipping of the whole block
of code including both function inlining and function-macro difference
reporting when one of the calls was a SimpLL abstraction (this should
apply only to the inlining), the second was the missing implementation
of the reporting when one of the instruction wasn't a call instruction.
(Both problems caused false empty diffs in some functions.)
=> SimpLL: Fixed function-macro difference reporting.

diffkemp/simpll/DebugInfo.cpp, diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/DifferentialFunctionComparator.h, diffkemp/simpll/ModuleComparator.h, diffkemp/simpll/Utils.cpp, diffkemp/simpll/Utils.h
This PR adds code that attempts to reconstruct the original arguments for inline assembly in a C-like syntax to be shown alongside the differing assembly code.
There are several cases where this produces slightly different code from the original source, since some of the information is lost when compiling from C to LLVM IR; however it is sufficient to enable the user to identify the actual arguments in the C source code.
The function supports both local and global variables (including function arguments), load instructions, casts, extensions and has an incomplete support for GEPs.
The code uses DebugInfo to get GEP index names - because of this StructFieldNames generating was extended to include cases when indices are equal. (The cases that do not work, i.e. show the index number, are …
=> Add inline assembly arguments to syntax diff.

diffkemp/simpll/Transforms.cpp, diffkemp/simpll/passes/UnionHashGeneratorPass.cpp, diffkemp/simpll/passes/UnionHashGeneratorPass.h
This PR adds a pass that converts anonymous union type suffixes to ones based on the hash of the dump of the type excluding its clang-generated name. This ensures that union types that are the same will have the same name even in cases when they are in different modules and were generated in a different order.
The consistent type naming is currently only needed for the FunctionAbstractionsGenerator hashes (besides better human readability of the LLVM IR); it may become redundant in the future in case a better implementation of the hash function is created.
=> SimpLL: Name anonymous union types according to their content.

diffkemp/syndiff/function_syntax_diff.py
This is needed for some files in the kernel that contain names of
developers in comments that contain non-ASCII characters.
=> function_syntax_diff: load source as UTF-8.

README.md, diffkemp/diffkemp.py, diffkemp/function_list.py, diffkemp/llvm_ir/kernel_module.py, diffkemp/llvm_ir/kernel_source.py, diffkemp/llvm_ir/llvm_sysctl_module.py, tests/unit_tests/function_list_test.py
This mainly requires changing layout of the YAML file generated in the
snapshot:
- functions can be split into groups (by sysctl option)
- apart from LLVM file, each function has a global variable (in case it
is a function using the sysctl data variable) and a tag that contains
explanation why the function belongs to the given group
- in case only a list of functions is compared, a single group with
`None` key is created
Also, `generate` and `compare` functions are reworked to handle
functions split into groups.
=> Support comparing sysctl options

diffkemp/config.py, diffkemp/diffkemp.py, diffkemp/semdiff/function_diff.py, diffkemp/simpll/Config.cpp, diffkemp/simpll/Config.h, diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/DifferentialFunctionComparator.h, diffkemp/simpll/ModuleComparator.cpp, diffkemp/simpll/ModuleComparator.h, diffkemp/simpll/SourceCodeUtils.cpp, diffkemp/simpll/SourceCodeUtils.h, diffkemp/simpll/Transforms.cpp, diffkemp/simpll/Utils.cpp, diffkemp/simpll/Utils.h, diffkemp/simpll/simpll.py, tests/regression/task_spec.py, tests/unit_tests/function_syntax_diff_test.py
This PR adds support for getting macro parameters and arguments from DebugInfo to SourceCodeUtils. This is done by parsing of macro bodies (arguments) and full macro names (parameters) using the functions originally created for ignored macro detection. (Any parameter names in the arguments are expanded using the fields of the parent macro, ensuring the arguments from the use of the parent macro get to the differing macros.)
This feature is then used to expand macro names created by joining an argument with a name template with the ## preprocessor symbol, allowing SimpLL to follow macros in many cases where it previously wasn't possible (this directly fixes several empty diff cases).
Note: Because inline assembly differences should now be detected in macros in most cases showing the raw …
=> Macro argument/parameter extraction

diffkemp/llvm_ir/kernel_module.py
The problem was in the regex for has_function, which previously caught incomplete function names (e.g. when a function with the name "apic", which is a global variable, was looked for, it found functions beginning with "apic", which caused diffkemp to think "apic" is a function).
=> Fix regex for has_function.

diffkemp/simpll/SourceCodeUtils.cpp
This fixes cases where the return expression is split to more
lines and a differing macro is on a different line than the first.
=> Parse return expressions properly in extractLineFromLocation.

README.md, diffkemp/diffkemp.py, diffkemp/function_list.py
Previously functions whose source code wasn't found by CScope
were not included into snapshots; this commit changes this in a
way that they are now included with their LLVM IR field set to
None, enabling adding them into statistics as unknown in the
compare phase.
=> Bring back unknown functions.

diffkemp/simpll/Utils.cpp, diffkemp/simpll/Utils.h, tools/func_comparator_return_vals.gdb
Note: the script is supposed to be used like this:
```bash
gdb --batch --command=gdb/returns.gdb --args <simpll_command>
````
Additional functions may use `PrintReturnValueBreakpoint` in case they compare subclasses of `cmpValues`; otherwise a new class has to be written (possibly creating a parent class from which both `PrintReturnValueBreakpoint` and the new class will inherit) alongside a dump function for the type.
=> Added debugging scripts.

diffkemp/llvm_ir/kernel_module.py
This fixes the merging of empty functions with different parameter
types that causes call instruction comparison to report non-equal.
Statistics show that applying this pass causes more false positives than it fixes (I actually don't know  any cases when the pass helps).
=> Do not merge functions after linking.

diffkemp/simpll/Utils.cpp
This causes an empty diff in one of the KABI functions from 7.6 to 7.7, because an alias call is falsely detected as an indirect call in one of the modules, creating an artificial difference by being replaced by a SimpLL abstraction.
=> SimpLL: Support aliases in getCalledFunction.

diffkemp/simpll/DebugInfo.cpp, diffkemp/simpll/DebugInfo.h, diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/Transforms.cpp, diffkemp/simpll/Utils.cpp, diffkemp/simpll/Utils.h
This PR adds a local variable map to DebugInfo which allows to look up a local variable by its name. This is used in a function that attempts to get the type of a variable (either local or global) by its identifier. This function is then used to retrive the type of the value in a sizeof expression and the type is subsequently compared both by cmpTypes and by type name (in case it is a structure type), allowing comparing sizeofs with a value of the same type as its parameter to be compared as equal (this helps to avoid false positives in KABI comparison).
=> Compare sizeofs by value type names

diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/ModuleComparator.cpp, diffkemp/simpll/SourceCodeUtils.cpp, diffkemp/simpll/Utils.cpp, diffkemp/simpll/Utils.h
Adds indentation to debugging prints during function comparison. Each such print should be moved by two spaces if referenced from another compared function.
Closes #66.
=> SimpLL: Indent info during comparison

diffkemp/simpll/ModuleComparator.cpp
Instead of simplifying both functions after every inlining, run the simplification after all inlinings are done. This prevents from double simplification of the first function which may cause inconsistency with the second function.
=> SimpLL: improve simplification after inlining

diffkemp/syndiff/function_syntax_diff.py
This can occur, e.g., if the function definition is generated from a one line macro. In such case, function_syntax_diff cannot extract the definition and throws an exception.
This prevents the exception from occurring by returning an error message instead of the diff.
This is a workaround for #100.
=> Do not fail in syntax_diff if function definition cannot be found

diffkemp/diffkemp.py, diffkemp/llvm_ir/kernel_source.py
The PR introduces 2 optimisations:
1. Instead of copying the CScope database from kernel to snapshot, it is re-built in the snapshot. This is much more space efficient.
2. Source priorities are fixed (see second commit).
=> Source finding optimisation

diffkemp/simpll/DifferentialFunctionComparator.cpp
- ignore differences in attributes (always compare attribute lists as equal)
- distinguish boolean from other integer types even when comparing the control flow only
=> Improve comparing attributes and integer types

diffkemp/simpll/Transforms.cpp, diffkemp/simpll/passes/MergeNumberedFunctionsPass.cpp, diffkemp/simpll/passes/MergeNumberedFunctionsPass.h
The pass merges functions that differ only in name number suffix and
have the same type together into one function without the suffix.
This fixes cases when multiple diffs between numbered versions of the
same function are passed to DiffKemp, which may show the wrong one (it
shows only one of them) and some other problems in function comparison.
=> SimpLL: Added custom pass for function merging.

README.md, diffkemp/diffkemp.py, diffkemp/syndiff/function_syntax_diff.py
By default, diffs and callstacks are printed to files. A single file is created for each compared symbol that is different. In case that the groups are used, there is a separate directory for each group.
All diff files (and group directories) are stored inside a directory that can be specified from the command line.
If there are unknown or error results, these are always printed to stdout.
=> Improve printing diffs to files

diffkemp/diffkemp.py, diffkemp/semdiff/result.py, diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/ModuleComparator.cpp, diffkemp/simpll/ModuleComparator.h, diffkemp/simpll/Output.cpp, diffkemp/simpll/Output.h, diffkemp/simpll/SimpLL.cpp, diffkemp/simpll/Transforms.cpp, diffkemp/simpll/Transforms.h, diffkemp/simpll/Utils.cpp, diffkemp/simpll/Utils.h, diffkemp/simpll/passes/FieldAccessFunctionGenerator.cpp, diffkemp/simpll/passes/FieldAccessFunctionGenerator.h, diffkemp/simpll/passes/FunctionAbstractionsGenerator.cpp, diffkemp/simpll/passes/FunctionAbstractionsGenerator.h, diffkemp/simpll/passes/MergeNumberedFunctionsPass.cpp, diffkemp/simpll/simpll.py
The problem was that there were some cases when the call instructions
differed in a way that didn't show up in the C source code (e.g. the
return type changed without affecting the call), leading to inlining,
but the original difference was inside the inlined function (and after
the inlining it was reported in the parent one).
The fix uses a similar technique to syntax difference handling - in case
two functions with the same name are being inlined, they are compared
using ModuleComparator and in case both the original and the inlined
functions are compared as non-equal, the difference between the original
ones is marked as covered (in case the original functions are equal after
the inlining, the difference of the inlined function is removed.
Note: the variables `missingDefs`, …
=> SimpLL: Fix inlining causing empty diffs.

diffkemp/simpll/SourceCodeUtils.cpp
The problem was in the code that extracts inline assembly arguments
from C source code - it didn't check whether a starting bracket was
found and the value was passed directly to getSubstringToMatchingBracket.
Note: the problem didn't appear when using a standard C++ library that
does not assert on invalid string index.
=> SimpLL: Fix bug in findInlineAssemblySourceArguments.

.travis.yml
This can be useful if code format checks fail since there is no need to re-run tests for all versions, which takes a long time.
=> Travis CI: move code format checks into a separate job

diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/DifferentialFunctionComparator.h, diffkemp/simpll/ModuleComparator.cpp
If the call instructions have a difference that is detected before the
code get to the comparison of the functions itself, call cmpGlobalValues
to explicitly compare them and mark the parent function as covered in
case cmpGlobalValues returns zero. (This prevents false empty diffs in
cases when the difference in the parent function is actually in the
called function in the C source code.)
Fixes #120.
=> SimpLL: Better call comparison.

diffkemp/llvm_ir/kernel_source.py, diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/ModuleComparator.h, diffkemp/simpll/Transforms.cpp, diffkemp/simpll/passes/FunctionAbstractionsGenerator.cpp, diffkemp/simpll/passes/FunctionAbstractionsGenerator.h, diffkemp/simpll/passes/RemoveUnusedReturnValuesPass.cpp
Previously each inline assembly code abstraction had a correspoding
entry in a map contaning its (function) name and its content. This
caused a bug when the content wasn't found after the function was
renamed by a pass.
To handle this, the assembly code was moved to a metadata node attached
to the abstraction function together with the constraint, which is now
also used while comparing inline assembly code abstraction calls.
This fixes #124.
=> SimpLL: Replace asm to value maps with metadata.

.gitignore, diffkemp/simpll/DebugInfo.cpp, diffkemp/simpll/Transforms.cpp, diffkemp/simpll/passes/ControlFlowSlicer.cpp, diffkemp/simpll/passes/FunctionAbstractionsGenerator.cpp, diffkemp/simpll/passes/RemoveUnusedReturnValuesPass.cpp, diffkemp/simpll/passes/UnifyMemcpyPass.cpp
- ControlFlowSlicer: print of which instructions are removed by the pass.
- FunctionAbstractionsGenerator: print which call instruction is replaced by which abstraction
- RemoveUnusedReturnValuesPass: indent messages about replacing of call instructions so that it is clear which function they belong to. Remove unnecessary messages.
- UnifyMemcpyPass: Remove all messages (they are not useful).
Closes #68
=> SimpLL: clean messages printed by passes

diffkemp/simpll/passes/CalledFunctionsAnalysis.cpp
Before this fix, if a function was stored inside a global constant that was used in a bitcast operator, the function was not added to called functions (due to missing support of the bitcast operator).
This bug caused an error in comparing `2.6.32-696.el6` and `2.6.32-754.el6` in function `shmem_file_setup`.
=> SimpLL: fix bug in CalledFunctionsAnalysis

diffkemp/llvm_ir/build_llvm.py, diffkemp/simpll/passes/CalledFunctionsAnalysis.cpp
The value of the macros DEBUG_HASH and DEBUG_HASH2 is generated by
Kbuild, does not represent a semantic difference (other that for
debugging purposes) and breaks comparison, because the macro is outside
a call instruction and therefore can't be detected by SourceCodeUtils in
SimpLL.
Therefore the generate phase is modified not to use the generate value
and use 1 instead for all modules in the kernel.
Also includes a small enchancement of CalledFunctionsAnalysis.
Note: the debug hashes caused a large number of false positives between versions `2.6.32-696.el6` and `2.6.32-754.el6`.
=> Remove debug hashes

diffkemp/simpll/SourceCodeUtils.cpp
Use DICompileUnit instead of module as the key of the cache map (there
may be multiple compile units in one module when the module was
generated by linking).
=> SimpLL: Fix bug in macro map caching.

diffkemp/simpll/DifferentialFunctionComparator.cpp
When comparing call instructions, if one of them contains a bitcast
operator, the called function was not found properly.
=> SimpLL: fix bug in DifferentialFunctionComparator

tests/regression/syntax_diff_test.py, tests/regression/task_spec.py, tests/regression/test_specs/rhel-73-74.yaml, tests/regression/test_specs/rhel-74-75.yaml, tests/regression/test_specs/rhel-75-76.yaml
Add support for regression tests for checking correctness of syntax
diffs. This is implemented as an extension to the existing regression
test infrastructure.
The individual tests can be specified using the "syntax_diff" key in the
appropriate YAML spec file (see existing tests for inspiration).
Currently supports only checking of differences in macros and inline
assembly code.
Includes also few initial tests, tips for additional tests are welcome.
=> Tests for correctness of syntax diffs

diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/ModuleComparator.h, diffkemp/simpll/Transforms.h, diffkemp/simpll/Utils.h, tests/regression/test_specs/rhel-74-75.yaml
If there is a syntactic difference in names of constant global variables
that are declared as external, sources that define these constants are
found, linked to the current module, and the analysis rerun. 
This closes #43.
Note: Implementation of MissingDefs is changed from const *Function pair
to const *GlobalValue pair.
=> Linking externally defined global constants 

diffkemp/simpll/Utils.cpp, tests/regression/test_specs/rhel-73-74.yaml, tests/regression/test_specs/rhel-74-75-cfo.yaml, tests/regression/test_specs/rhel-74-75.yaml, tests/regression/test_specs/rhel-75-76-cfo.yaml, tests/regression/test_specs/rhel-75-76.yaml
There are some bugs in control-flow-only slicing that cause some tests that do not need it to fail. Sometimes, this happens non-deterministically and on some LLVM versions only. Therefore, we put
all regression tests that require the control-flow-only flag into separate spec files.
Also, fix indentation of all YAML spec files to 2 spaces.
=> Regression tests: separate control-flow-only tests

diffkemp/simpll/DebugInfo.cpp, diffkemp/simpll/DifferentialFunctionComparator.cpp
The PR contains two parts:
- fix multiple bugs in comparison of field access abstractions that caused abstractions to be compared as equal even if they were not (ultimately causing false negatives)
- support finding index alignment in structures that contain padding fields (fields that have no size, just an alignment)
=> Fix bugs in comparing GEP instructions

docker/diffkemp-devel/run-container.sh
It is necessary that we support podman for eg. new versions of Fedora. If the docker command is not found on the host, the script will try to use podman instead.
=> Docker: Add podman support to the starting script

diffkemp/diffkemp.py, diffkemp/semdiff/result.py, diffkemp/simpll/Config.cpp, diffkemp/simpll/Config.h, diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/DifferentialFunctionComparator.h, diffkemp/simpll/ModuleComparator.cpp, diffkemp/simpll/ModuleComparator.h, diffkemp/simpll/SourceCodeUtils.cpp, diffkemp/simpll/SourceCodeUtils.h, diffkemp/simpll/Transforms.cpp, diffkemp/simpll/passes/FieldAccessFunctionGenerator.cpp
This PR features two major SimpLL optimisations:
- finding macro differences: macro definitions extracted from debug info and macro usages for each program location are cached so that every macro and every line needs to be parsed only once
- field access abstractions: abstractions are created only if all GEPs have constant indices and comparison of two abstractions having a single instruction is done using the original `cmpGEPs` method
Also, the diffs found within a KABI symbol are sorted so that comparison of large logs is easier.
=> SimpLL optimisations

diffkemp/simpll/ModuleComparator.cpp, diffkemp/simpll/Result.h
The bug is caused by updating a set representing a call stack while iterating it. Previously, an element was removed out of the set, altered (marked as weak), and then inserted again. This fix marks the updated field as mutable and does the update in-place.
This bug occurred at Fedora 30 while testing comparison of 4.18.0-80 -> 4.18.0-147.
=> SimpLL: fix bug in marking inlined call as weak

diffkemp/llvm_ir/build_llvm.py, diffkemp/simpll/passes/SimplifyKernelFunctionCallsPass.cpp
There are 2 features implemented:
- `asm goto` is used in multiple headers in kernel 5.x - all occurrences are now replaced
- when compiling a single file into LLVM, it is needed to find a `gcc` command (until now, also `ld` commands were searched for, which caused the compilation to fail)
Also a bug occurring in comparison of 5.2 and 5.3 kernels is fixed.
=> Support kernel 5.x compilation

diffkemp/simpll/DifferentialFunctionComparator.cpp
In the case when two constant global variables with a different name and
without an initializer are compared, an explicit return statement is
necessary, otherwise undefined behavior will occur.
=> SimpLL: Fix bug in cmpGlobalValues.

.gitignore, .travis.yml, CMakeLists.txt, diffkemp/simpll/CMakeLists.txt, diffkemp/simpll/Config.h, tests/unit_tests/simpll/CMakeLists.txt, tests/unit_tests/simpll/CMakeLists.txt.in, tests/unit_tests/simpll/DifferentialFunctionComparatorTest.cpp, tests/unit_tests/simpll/SimpLLTest.cpp, tools/check-clang-format.sh
Currently tests cover only DifferentialFunctionComparator (without macro and type differences) and need LLVM 8 or greater because of differences in LLVM classes (especially in debug information classes).
=> Add unit tests for SimpLL.

.travis.yml, diffkemp/llvm_ir/kernel_source.py, diffkemp/simpll/simpll.py, diffkemp/snapshot.py
This PR contains several optimisations in the Python part of DiffKemp.
1. libyaml bindings are used to load YAMLs instead of the native Python implementation if available.
2. A bug causing the complexity of snapshot loading to be quadratic is fixed.
3. CScope results are cached, allowing them to be reused in the compare phase.
According to profiler results 97 % of the time in DiffKemp is now in external processes, most of it in SimpLL.
=> Python optimisations

.travis.yml, diffkemp/simpll/llvm-lib/10/FunctionComparator.cpp, diffkemp/simpll/llvm-lib/10/FunctionComparator.h, diffkemp/simpll/passes/UnifyMemcpyPass.cpp
FunctionComparator from LLVM 10 was added to llvm-lib (it is actually
the same as in LLVM 9) and a now depracated call to
LLVMBuilder::CreateMemCpy was replaced with a call to the new function.
=> Support LLVM 10.

diffkemp/llvm_ir/build_llvm.py, diffkemp/llvm_ir/kernel_source.py, diffkemp/semdiff/caching.py, diffkemp/semdiff/function_diff.py, tests/unit_tests/caching_test.py
The proposed fixes are:
- disable `asm inline` constructs not supported by older LLVM versions
- always pass relative path to the object file to `make`
- if an LLVM module includes a file outside of the kernel source tree, do not copy it into the snapshot
- when missing definitions are found, and the linking is successful, do not merge the comparison graphs since the new one contains invalid results that will be re-computed
=> Several improvements and fixes

diffkemp/snapshot.py, tests/unit_tests/snapshot_test.py
By default, datetime objects are treated as local times which may cause problems when compared to source file mtime that is in UTC.
These changes force to always use UTC in snapshots.
=> Always use UTC time in snapshots

diffkemp/simpll/SourceCodeUtils.cpp
The function `getSubstringToMatchingBracket` may receive position equal to `string::npos`. In such case, it must return an empty string to prevent crash.
This situation may happen when a function is used in code without brackets, which is, e.g., case for the function `__dynamic_dev_dbg` occurring as an argument of macro `_dynamic_func_call` in newer kernels.
=> SimpLL: fix bug in SourceCodeUtils

.travis.yml
The ubuntu-toolchain-r-test specifier does not seem to be supported anymore.
=> Travis CI: use explicit address for testing PPA

diffkemp/llvm_ir/build_llvm.py
There may be warnings when disabling goto features if the altered header does not exist in the given kernel version. Therefore we redirect the sed stderr to /dev/null.
=> LLVM build: do not show sed warnings

diffkemp/simpll/ModuleAnalysis.cpp, diffkemp/simpll/Utils.cpp, diffkemp/simpll/Utils.h, diffkemp/simpll/passes/RemoveUnusedReturnValuesPass.cpp, diffkemp/simpll/passes/SeparateCallsToBitcastPass.cpp, diffkemp/simpll/passes/SeparateCallsToBitcastPass.h, diffkemp/simpll/passes/SimplifyKernelFunctionCallsPass.cpp
The SeparateCallsToBitcastPass pass separates bitcasts from calls to
bitcast operators by inserting new bitcast instructions that transform
function arguments and the return value separately.
This change makes these calls inlinable during the comparison phase. Fixes #42.
Example:
`call void bitcast (void (%struct.super_block.30*)* @fsnotify_unmount_inodes to void (%struct.super_block*)*)(%struct.super_block* %0), !dbg !25663`
will be changed to:
`%12 = bitcast %struct.super_block* %0 to %struct.super_block.30*, !dbg !25663`
`call void @fsnotify_unmount_inodes(%struct.super_block.30* %12), !dbg !25663`
=> SimpLL: Add SeparateCallsToBitcastPass pass

diffkemp/llvm_ir/build_llvm.py, diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/DifferentialFunctionComparator.h, diffkemp/simpll/llvm-lib/10/FunctionComparator.h, diffkemp/simpll/llvm-lib/5/FunctionComparator.h, diffkemp/simpll/llvm-lib/6/FunctionComparator.h, diffkemp/simpll/llvm-lib/7/FunctionComparator.h, diffkemp/simpll/llvm-lib/8/FunctionComparator.h, diffkemp/simpll/llvm-lib/9/FunctionComparator.h
This change allows to handle refactorings of the form:
if (C) {B1} {B2} -> if (!C) {B2} {B1}
including cases when `return` or `continue` is used in one of the branches.
The PR contains several features:
- Handling comparison of inverse branch conditions. This is done by collecting pairs of `cmp` instructions with inverse predicates and if such instructions are used as conditions in `br` instructions, successors for one of the branches are swapped.
- Improved comparison of PHI instructions that have reordered incoming value/block pairs. This is done by postponing PHI comparison into the end after all other values and blocks were compared.
- Running the `-mergereturn` pass in `opt`. This is to improve handling of situations when an additional `return` is added due to refactoring.
See …
=> Handle refactoring by inverting if conditions

rpm/diffkemp.spec
Run SimpLL unit tests in the check phase (these do not need external
kernel sources present).
Also, Git is required for building because of GTest.
=> RPM: add %check phase

diffkemp/simpll/passes/SeparateCallsToBitcastPass.cpp
The new instructions with bitcasted arguments should be always inserted before the old call instruction to get them in the correct order.
Moreover, if an argument is not transformed into an instruction (since it is not casted), the cast in the original code may fail.
=> SimpLL: bitcast calls: fix order of casted args

diffkemp/semdiff/function_diff.py
This error caused that the `--output-llvm-ir` CLI option did not work.
=> Pass forgotten param output_llvm_ir to run_simpll

diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/DifferentialFunctionComparator.h, tests/unit_tests/simpll/DifferentialFunctionComparatorTest.cpp
This PR implements two related refactorings:
1. Move the code for comparison of instructions and of all their operands from `cmpBasicBlocks` into a newly created function `cmpOperationsWithOperands`. This enables the point 2, since the functions for finding syntax differences (differences in macros, inline assembly code, and in types) do not have to be called from two places (once from `cmpOperations` and once from `cmpBasicBlocks` for arguments) anymore.
2. Move all the code for finding syntax differences and for setting functions to be inlined into a single function `findDifferences` that is called from `cmpBasicBlocks` after `cmpOperationsWithOperands` returns a difference. 
Also, a separate function `findTypeDifferenceInFieldAccess` for finding differences in chained field …
=> Refactor comparing of instructions and basic blocks

diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/DifferentialFunctionComparator.h
Added pair of const Instructions* to DifferentialFunctionComparator
where are stored first differing instructions of nonequal functions.
Also implemented function DifferentialFunctionComparator::equal that
compares two given instructions and decide whether they are equal
(returns true) or not (returns false).
=> SimpLL: Pointers to first differing instructions

.travis.yml, diffkemp/simpll/CMakeLists.txt, diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/Output.cpp
Includes three small changes concerning the compilation process:
- Add colour diagnostic flags to CMakeLists for both GCC and Clang since a pseudo-terminal gets used with Ninja, which disables output colour coding by default.
- Fix warnings reported ba Clang. These include the removal of template nesting in `Output.cpp` and an unsigned integer subtraction fix in `DifferentialFunctionComparator.cpp`.
- Add Clang compilation into the CI configuration (for the latest version of LLVM only).
=> Add colored compilation with Clang support

diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/llvm-lib/10/LICENSE, diffkemp/simpll/llvm-lib/5/LICENSE, diffkemp/simpll/llvm-lib/6/LICENSE, diffkemp/simpll/llvm-lib/7/LICENSE, diffkemp/simpll/llvm-lib/8/LICENSE, diffkemp/simpll/llvm-lib/9/LICENSE
Adds original LLVM LICENSE files into the `llvm-lib` version subdirectories, and references those LICENSE files from the `DifferentialFunctionComparator` (where applicable).
=> SimpLL: Add LLVM licensing information

diffkemp/simpll/DebugInfo.cpp, diffkemp/simpll/DebugInfo.h, diffkemp/simpll/DifferentialFunctionComparator.cpp
During comparison of two GEPs for array element access is inequality
only in the number of elements of the accessed array, its not considered
anymore as a semantic change if the index has an enumeration type.
This closes #146.
=> Difference in the number of elements of two enums

CMakeLists.txt, diffkemp/simpll/CMakeLists.txt, diffkemp/simpll/simpll_build.py, tests/unit_tests/simpll/CMakeLists.txt, tests/unit_tests/simpll/DifferentialFunctionComparatorTest.cpp
To compile Diffkemp in macOS, we need explicitly add system libraries for linking. 
Also, it is needed to explicitly define C++14 standard.
By default, insertion to map makes copy in macOS. `Class Result` do not
have copy constructor, so it caused errors. Therefore, we use `emplace` to
fix it.
=> Adjusting compilation for macOS

.github/workflows/ci.yml, diffkemp/simpll/simpll_build.py
This is now required since GCC7 is not installed by default in the CI environment.
The change also required to explicitly set CFFI language to C++.
=> CI: install GCC7 manually

diffkemp/llvm_ir/build_llvm.py
Some GCC versions produce warnings when building older kernels, so we need to add `-Wno-error=...` to be able to compile those kernels.
=> Kernel build: do not fail on some warnings types

docker/diffkemp-devel/Dockerfile
- Keep only GCC 7, which is needed for compiling RHEL 7 kernels.
- Update alternatives for `x86_64-linux-gnu-gcc/-g++` which are used in CFFI build process.
=> Container image: remove conflicting GCC versions

diffkemp/diffkemp.py, diffkemp/semdiff/result.py
Adds the total elapsed time in seconds to the reported statistics. The timer starts when the primary instance of `Result` gets created and ends just before the statistics get reported.
Example `--report-stat` output:
```
Statistics
----------
Total symbols: 471
Equal:         356 (76%)
Not equal:     85 (18%)
(empty diff):  1 (0%)
Unknown:       25 (5%)
Errors:        5 (1%)
Elapsed time:            233.42 s
Functions compared:      3411
Total differences:       93
In functions:            81 (87%)
In types:                5 (5%)
In macros:               7 (8%)
In inline assembly code: 0 (0%)
Empty diffs:             4 (4%)
```
=> Add elapsed time to the reported statistics

.github/workflows/ci.yml
Requires latest [rhel-kernel-get](https://github.com/viktormalik/rhel-kernel-get)
Closes #192.
=> CI: use Ubuntu 18.04

diffkemp/config.py, diffkemp/diffkemp.py, diffkemp/semdiff/function_diff.py, diffkemp/simpll/Config.cpp, diffkemp/simpll/Config.h, diffkemp/simpll/DebugInfo.cpp, diffkemp/simpll/SourceCodeUtils.cpp, diffkemp/simpll/library/FFI.cpp, diffkemp/simpll/library/FFI.h, diffkemp/simpll/passes/ControlFlowSlicer.cpp, diffkemp/simpll/passes/FunctionAbstractionsGenerator.cpp, diffkemp/simpll/passes/RemoveUnusedReturnValuesPass.cpp, diffkemp/simpll/passes/SeparateCallsToBitcastPass.cpp, diffkemp/simpll/passes/VarDependencySlicer.cpp, diffkemp/simpll/simpll.py
Added a new, more verbose verbosity level.
This new verbosity level can be selected by using a `-vv` parameter.
So far I've only moved each passes' debug output to this new level. Other debug messages stay on the same level as before.
Resolves #36
=> Add verbose levels

diffkemp/semdiff/function_diff.py, diffkemp/simpll/ModuleAnalysis.cpp, diffkemp/simpll/ModuleComparator.cpp, diffkemp/simpll/ModuleComparator.h, diffkemp/simpll/Utils.cpp
Fixes #197
I'm not quite sure which `"syntactic"` strings should've been changed to `"semantic"` so I might've changed some that should've stayed and didn't change some that should be changed. Could you have a look at that? Particularly in `semdiff/function_diff.py`.
=> Fix color output

diffkemp/simpll/DebugInfo.cpp, diffkemp/simpll/DebugInfo.h, diffkemp/simpll/ModuleAnalysis.cpp, diffkemp/simpll/passes/ControlFlowSlicer.cpp, diffkemp/simpll/passes/FunctionAbstractionsGenerator.cpp, diffkemp/simpll/passes/RemoveUnusedReturnValuesPass.cpp, diffkemp/simpll/passes/VarDependencySlicer.cpp
Resolves #67 
Adds these messages:
```
Analysing debugging information...
Preprocessing {mod_name}...
Slicing control-flow-only statements...
Generating function abstractions in module {mod_name}...
Removing unused return values in module {mod_name}...
Slicing {fun_name} w.r.t. value of {var_name}...
```
=> SimpLL: Print info about analysis phases

diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/DifferentialFunctionComparator.h, tests/unit_tests/simpll/DifferentialFunctionComparatorTest.cpp
When getting a replacement value for an ignored instruction in `cmpValues`, besides querying the `ignoredInstructions` map, we allow to skip bitcast and zero GEP operators. The problem is that the replacing value may not be already synchronized and hence an incorrect synchronisation may be created by `cmpValues`.
This fixes the above problem by checking that if the replacing value is an instruction, it is already synchronised.
See the added unit test for an example.
=> Fix instruction ignoring bug

.github/workflows/ci.yml, diffkemp/simpll/DebugInfo.cpp, diffkemp/simpll/ModuleAnalysis.cpp, diffkemp/simpll/Utils.cpp, diffkemp/simpll/library/FFI.cpp, diffkemp/simpll/llvm-lib/13/FunctionComparator.cpp, diffkemp/simpll/llvm-lib/13/FunctionComparator.h, diffkemp/simpll/passes/VarDependencySlicer.cpp, docker/diffkemp-devel/Dockerfile, tests/unit_tests/simpll/passes/CalledFunctionsAnalysisTest.cpp, tests/unit_tests/simpll/passes/FunctionAbstractionsGeneratorTest.cpp, tests/unit_tests/simpll/passes/MergeNumberedFunctionsPassTest.cpp, tests/unit_tests/simpll/passes/ReduceFunctionMetadataPassTest.cpp, tests/unit_tests/simpll/passes/RemoveLifetimeCallPassTest.cpp, tests/unit_tests/simpll/passes/RemoveUnusedReturnValuesPassTest.cpp, tests/unit_tests/simpll/passes/SeparateCallsToBitcastPassTest.cpp, tests/unit_tests/simpll/passes/SimplifyKernelFunctionCallsPassTest.cpp, tests/unit_tests/simpll/passes/SimplifyKernelGlobalsPassTest.cpp, tests/unit_tests/simpll/passes/StructHashGeneratorPassTest.cpp, tests/unit_tests/simpll/passes/StructureSizeAnalysisTest.cpp, tests/unit_tests/simpll/passes/UnifyMemcpyPassTest.cpp, tests/unit_tests/simpll/passes/VarDependencySlicerTest.cpp
The PassManager(bool) constructor is no longer supported.
The sys::fs::F_None enum value was replaced with sys::fs::OF_None.
The CloneFunctionInto function now takes a finer grained CloneFunctionChangeType
instead of a boolean to specify the scope of changes.
The Dockerfile was updated to Ubuntu 20.04 (Focal), which supports LLVM 13.
Github CI was also updated to Focal.
Resolves #209.
=> Add support for LLVM 13

diffkemp/simpll/passes/SimplifyKernelGlobalsPass.cpp
`SimplifyKernelGlobalsPass` removes global variables having the `__ksym` prefix. Before erasing such a global, we need to replace all its uses by `nullptr` so that there are no memory leaks.
This should also fix a bug that non-determinisically appears for the regression test `rhel-73-74_debugfs_create_u32` with LLVM 13.
=> Replace uses of a global before erasing it (fix memory error)

diffkemp/diffkemp.py, diffkemp/snapshot.py, tests/unit_tests/snapshot_test.py
This PR resolves #199.
When running `diffkemp generate`, saves the current LLVM **major** version into the snapshot YAML file.
When running `diffkemp compare`, checks whether the major version in use now is the same as in both snapshots. If not, fails.
There is no need to check for minor version differences, as [minor versions are never released](http://blog.llvm.org/2016/12/llvms-new-versioning-scheme.html). Furthermore, different patch versions should be compatible, so they are not checked either.
=> Save LLVM version when running diffkemp generate

diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/Utils.cpp, diffkemp/simpll/Utils.h, tests/unit_tests/simpll/DifferentialFunctionComparatorTest.cpp
Until now, the only supported situation related to inverse condition branches was when conditions had inverse operations
(e.g. `eq` and `ne`).
This PR covers a situation when one condition is a negation (using `xor`) of the other. Also handles a combination of the two approaches - conditions have inverse operations, then one of them is negated, and the final `br` instructions have the same successors order (i.e. not swapped).
Also adds unit tests for both supported cases.
=> Improve handling inverse condition branches

diffkemp/simpll/simpll.py, diffkemp/simpll/simpll_build.py
We could support multiple builds using an environment variable similarly to e.g., [Flask](https://flask.palletsprojects.com/en/2.0.x/config/). The usage of a default build directory would remain the same, usage of a custom one would be as follows:
```bash
mkdir custom_build                       # assume that the custom build is in this directory
export SIMPLL_BUILD_DIR=custom_build     # set the environment variable
pip install -e .                         # install normally (but within the same environment)
bin/diffkemp                             # use diffkemp normally (still in the same environment)
```
After researching the possible options, this seems like the only viable way of allowing multiple builds.
Let me know if this is acceptable.
If accepted, this PR resolves #211.
=> WIP: Allow multiple builds using an environment variable

diffkemp/diffkemp.py, diffkemp/snapshot.py, tests/unit_tests/snapshot_test.py
In some cases, it makes sense to deliberately omit storing the path to source dir in snapshot. An example is when the path would be the same for both compared snapshots (e.g. when comparing different Git refs) where storing the path could lead to false negative errors. This also facilitates moving snapshots independently from sources.
=> Allow not saving path to source to the snapshot

diffkemp/simpll/ModuleComparator.cpp, diffkemp/simpll/ModuleComparator.h, diffkemp/simpll/Utils.cpp, diffkemp/simpll/Utils.h
There is a problem that if a pair of called functions is compared as non equal, but then they are inlined which makes the caller functions to be compared as equal, the non-equal result may pollute the overall output. This is solved by removing the inlined functions comparison verdict.
Also, there was a lot of repetition in the code handling function inlining, so it made sense to refactor it a bit.
=> Small improvement and refactoring of inlining

.github/workflows/ci.yml, diffkemp/simpll/DebugInfo.cpp, diffkemp/simpll/DebugInfo.h, diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/InstPatternComparator.cpp, diffkemp/simpll/InstPatternComparator.h, diffkemp/simpll/ModuleAnalysis.cpp, diffkemp/simpll/Utils.cpp, diffkemp/simpll/Utils.h, diffkemp/simpll/library/FFI.cpp, diffkemp/simpll/llvm-lib/14/FunctionComparator.cpp, diffkemp/simpll/llvm-lib/14/FunctionComparator.h, diffkemp/simpll/passes/FunctionAbstractionsGenerator.cpp, diffkemp/simpll/passes/RemoveUnusedReturnValuesPass.cpp, diffkemp/simpll/passes/SeparateCallsToBitcastPass.cpp, diffkemp/simpll/passes/SimplifyKernelFunctionCallsPass.cpp, diffkemp/simpll/passes/StructureDebugInfoAnalysis.cpp, diffkemp/simpll/passes/UnifyMemcpyPass.cpp, diffkemp/simpll/passes/VarDependencySlicer.cpp, docker/diffkemp-devel/Dockerfile, tests/unit_tests/simpll/DifferentialFunctionComparatorTest.cpp, tests/unit_tests/simpll/passes/CalledFunctionsAnalysisTest.cpp, tests/unit_tests/simpll/passes/FunctionAbstractionsGeneratorTest.cpp, tests/unit_tests/simpll/passes/RemoveUnusedReturnValuesPassTest.cpp, tests/unit_tests/simpll/passes/SeparateCallsToBitcastPassTest.cpp, tests/unit_tests/simpll/passes/SimplifyKernelFunctionCallsPassTest.cpp, tests/unit_tests/simpll/passes/StructureSizeAnalysisTest.cpp, tests/unit_tests/simpll/passes/UnifyMemcpyPassTest.cpp
- Replace the obsolete `LLVM::CallInst::getNumArgOperands` with `LLVM::CallInst::arg_size`
- Update the CI and the Dockerfile
- Remove all remaining support of LLVM 8 and lower (not supported since #216)
- Begin the transition to opaque pointers (replace calls to `LLVM::PointerType::getElementType` with `LLVM::PointerType::getPointerElementType` or remove them completely where easily possible)
I still see 2 remaining problematic points when it comes to transitioning to opaque pointers:
- The [`DifferentialFunctionComparator::cmpMemset`](https://github.com/viktormalik/diffkemp/blob/ecf57d4190a3631a7e71326c36114029caeb5ddb/diffkemp/simpll/DifferentialFunctionComparator.cpp#L1429) and [`DifferentialFunctionComparator::cmpAllocs`](https://github.com/viktormalik/diffkemp/blob/ecf57d4190a3631a7e …
=> Update to LLVM 14

diffkemp/llvm_ir/kernel_llvm_source_builder.py
Kernel has `-Werror` on by default, which causes LLVM IR build to fail when, e.g., building older kernels with newer GCC. Using `-w` suppresses all warnings and eliminates this issue.
=> Kernel builds: suppress all warnings

diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/DifferentialFunctionComparator.h, diffkemp/simpll/ModuleComparator.h, diffkemp/simpll/Utils.h, diffkemp/simpll/llvm-lib/10/FunctionComparator.h, diffkemp/simpll/llvm-lib/11/FunctionComparator.h, diffkemp/simpll/llvm-lib/12/FunctionComparator.h, diffkemp/simpll/llvm-lib/13/FunctionComparator.h, diffkemp/simpll/llvm-lib/14/FunctionComparator.h, diffkemp/simpll/llvm-lib/5/FunctionComparator.h, diffkemp/simpll/llvm-lib/6/FunctionComparator.h, diffkemp/simpll/llvm-lib/7/FunctionComparator.h, diffkemp/simpll/llvm-lib/8/FunctionComparator.h, diffkemp/simpll/llvm-lib/9/FunctionComparator.h, tests/unit_tests/simpll/DifferentialFunctionComparatorTest.cpp
A common refactoring is when a piece of code is moved into another part of the function (e.g. from inside the loop before the loop head). This helps to compare such a change as semantically equal.
Handling code relocations is done in 3 phases, they roughly correspond to states of the new enum `RelocationInfo::Status`.
- Relocation detection is run when a difference is found and no relocation has been found so far (status is `None`). Detection is done by trying to "skip" a block of code in one of the basic blocks and match the remaining parts of the blocks. If it succeeds, the relocation is stored.
- Relocation matching is run when a difference is found and there is a previously found potential relocation (state is `Stored`). In such a case, we reset the current instruction iterator to the …
=> Handle comparison of relocated code

.github/workflows/ci.yml, CMakeLists.txt, diffkemp/simpll/CMakeLists.txt, diffkemp/simpll/passes/VarDependencySlicer.cpp, tests/unit_tests/simpll/CMakeLists.txt, tests/unit_tests/simpll/DifferentialFunctionComparatorTest.cpp
This PR adds:
- fixes of all memory issues in Diffkemp (as reported by Valgrind and Address Sanitizer)
- the ability to compile Diffkemp with ASan using the `-DSANITIZE_ADDRESS=ON` option
- a CI run which compiles Diffkemp with ASan and runs unit tests
Resolves #218.
=> Fix memory issues and set up a CI run with Address sanitizer

.gitignore, README.md, diffkemp/cli.py, diffkemp/diffkemp.py, diffkemp/llvm_ir/kernel_llvm_source_builder.py, diffkemp/llvm_ir/kernel_source_tree.py, diffkemp/llvm_ir/llvm_source_finder.py, diffkemp/llvm_ir/single_llvm_finder.py, diffkemp/llvm_ir/source_tree.py, diffkemp/snapshot.py, tests/regression/task_spec.py, tests/unit_tests/function_syntax_diff_test.py, tests/unit_tests/kernel_module_test.py, tests/unit_tests/kernel_source_tree_test.py, tests/unit_tests/llvm_sysctl_module_test.py, tests/unit_tests/snapshot_test.py, tests/unit_tests/source_tree_test.py
The `generate` command covers too much functionality and is not easily extensible. Therefore, in this PR, it is split into (currently) 2 sub-commands:
- `build-kernel` - covering the current `--kernel-with-builder` option (creates snapshot from a Linux kernel source by building source files into LLVM IR on-the-fly)    
- `llvm-to-snapshot` - covering the current `--single-llvm-file` option, creates snapshot from a project pre-built into a single LLVM IR file
This way, new snapshot generation options (such as `build` added by #228) can be easily added with new sub-commands that may have their own options.
As a preparation step for this PR, I refactored a good portion of snapshot generation parts. In particular, I moved instantiation of `SourceTree` and `SourceFinder` objects out of the …
=> Split generate into multiple sub-commands

diffkemp/building/cc_wrapper.py
File `utils.py` moved from `diffkemp/simpll/` to `diffkemp/` in c75115d7d42f5958b3d56539c1f77dff063e8efd, so this import has to be fixed.
=> Fix invalid import in `get_cc_wrapper_path`

diffkemp/simpll/DifferentialFunctionComparator.cpp
Set CurrentLocL and CurrentLocR to nullptr when there is no debug info and handle nullptr when using these.
Fixes #240
=> SimpLL: Fix segfault with missing debug info

diffkemp/simpll/DebugInfo.cpp
The missing check caused a null dereference error when the function `GetElementPtrInst::getIndexedType` returns null. This apparently happens when the array of indices passed to the function is not valid for the passed source element type.
=> Add missing nullptr check to `extractAlignmentFromInstructions`

CMakeLists.txt, diffkemp/building/CMakeLists.txt, diffkemp/simpll/simpll_lib.py, rpm/diffkemp.spec, setup.py
Changelog:
- Reworked CLI interface (generate split into multiple commands)
- New command for analysing any Makefile-based projects
- Support for LLVM 14 and 15
- SimpLL used as a library by default
- Support for custom patterns
- Handling code relocations
- Improved handling of inverse branching conditions
- Prevent analysing snapshots with other LLVM version
Several changes were needed for this build:
- Allow using RPython as a Python2 module (`python2 -m rpython`) from CMake, since the `rpython` binary cannot be easily installed in Fedora for the RPM build.
- Update specfile to compile the CC wrapper with RPython. Since RPython is based on Python2 (which is not supported anymore), the RPython package and its dependent packages (Py) are downloaded manually during RPM build.
- Improve …
=> Release 0.4.0

docker/diffkemp-rpm-testing/Dockerfile
Allows to create a container image with a specific version of Fedora containing all DiffKemp dependencies and two kernels prepared for comparison.
When the container is run, it installs DiffKemp from RPM and performs build-kernel and compare commands.
Supports installation from Copr (default) and from a local RPM file (by mounting the RPM into the container and setting the DIFFKEMP_RPM env variable). See comment in the Dockerfile for usage.
=> Dockerfile for RPM testing

CMakeLists.txt, tools/simpll_clean.sh
When upgrading LLVM,  the `.ll` files in `kernel/` and `tests/regression/kernel_modules/` become deprecated. Similarly, `diffkemp/simpll/_simpll.abi3.so` has to be replaced. Up to now, we were not able to detect the upgrade and rebuild them automatically.
I propose to execute a simple script during CMake configuration. The script reads the LLVM version from `diffkemp/simpll/_simpll.abi3.so` (i.e. the version of LLVM against which `simpll` is linked) and the current system LLVM version. If they differ, all of the mentioned files are deleted.
=> Add a script that cleans up the environment after upgrading LLVM

diffkemp/building/cc_wrapper.py
Add -g to options always added to clang call, besides -S and -emit-llvm.
DiffKemp relies heavily on debug information for both finding source files to get diffs from and for handling structure types.
=> cc_wrapper: Always include -g option

.github/workflows/ci.yml
Apparently, issue #263 (which has been recently occurring non-deterministically in multiple branches) is caused by the lack of space in GitHub runners.
Github only [guarantees 14 GB of disk space ](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) in the runners. In practice, the available space is usually higher, but it does not suffice in some runs (just the `kernel` directory has 21 GB after all tests are run).
This PR attempts to solve the issue using the following workarounds and upgrades of the CI workflow:
-  At the beginning of `build-and-test` jobs, some unused software is deleted, namely .NET, Haskell, CodeQL, and Android SDK. This frees up to 20 GB of disk space. The solution is taken from [this …
=> Update CI workflow to save space

diffkemp/cli.py, diffkemp/config.py, diffkemp/diffkemp.py, diffkemp/semdiff/caching.py, diffkemp/semdiff/function_diff.py, diffkemp/snapshot.py, diffkemp/syndiff/function_syntax_diff.py, tests/regression/task_spec.py, tests/unit_tests/caching_test.py, tests/unit_tests/function_syntax_diff_test.py, tests/unit_tests/result_test.py, tests/unit_tests/snapshot_test.py
This PR adds two new command-line options to Diffkemp:
- `--no-show-diff`: The current default option is to **not** print syntactic differences. I propose that the default behaviour is that we **do** print them, and this option disables it.
- `--full-diff`:  This option causes Diffkemp to show syntactic differences even for functions that are semantically equal. This is useful when analyzing which functions with syntactic differences were successfully evaluated as semantically equal.
=> Add --full-diff and --no-show-diff command-line options

.github/workflows/ci.yml
I found out that `npm run build` (which is part of CI) does not fail if there is a coding style error in test source files, it only fails when there is a coding style error in the "app" sources.
This commit adds to CI an independent "test" of coding style using ESLint.
=> Viewer: Add code style checks to CI

.github/workflows/ci.yml, view/.eslintrc.yaml, view/.gitignore, view/cypress.config.js, view/cypress/support/component-index.html, view/cypress/support/component.js, view/package-lock.json, view/package.json, view/src/App.jsx, view/src/index.jsx, view/src/setup.jsx, view/src/tests/Callstack.cy.jsx
This PR adds tests for testing if calls in `Callstack` are properly aligned.
The tests use:
- [`getBoundingClientRect`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) method which provides info about DOM elements' position/coordinates,
- [Cypress](https://www.cypress.io/): FE testing tool which runs in/on the browser, it allows testing of components' visualisation (appearance, style).
=>  Viewer: Add tests for Callstack appearance

CMakeLists.txt, diffkemp/diffkemp.py, view/src/App.jsx
This PR makes it possible to run the result viewer when DiffKemp is installed to system (see #277).
Build of the viewer is installed directly to `/var/lib/diffkemp/view/build`, originally I wanted to use `CMAKE_INSTALL_LOCALSTATEDIR`  (= `var`) variable, but the problem would be in locating the directory when running `diffkemp view` because the exact location would be dependant on `CMAKE_INSTALL_PREFIX` variable.
When DiffKemp is installed, `diffkemp view` runs `serve` directly via `npx`, the impact is that when first running `diffkemp view` the user will be asked if it is ok to install `serve` package (if it is not installed).
Also, I was thinking (probably overthinking) when copying src files of a compared project to `build` directory for the result viewer, if the copied files should …
=> Viewer: Install build to system

CMakeLists.txt, README.md, docker/diffkemp-rpm-testing/Dockerfile, rpm/diffkemp.spec, setup.py
Changelog:
- New web-based viewer of found differences
- CLI options for built-in patterns
- Improved logging and debugging
- Support for LLVM 16
- Move to C++17
Also update `rpm/diffkemp-rpm-testing/Dockerfile` with recent changes of [rhel-kernel-get](https://github.com/viktormalik/rhel-kernel-get) and some tweaks to be able to test the result viewer.
Add @PLukas2018 (author of the result viewer) to contributors.
=> Release 0.5.0

.github/workflows/ci.yml, README.md
I discovered a few places where was used the old name (with `.py` extension) of `rhel-kernel-get` script, the most problematic is in `ci.yml`. This PR updates the name.
=> Update name of rhel-kernel-get script

.github/workflows/ci.yml, rpm/diffkemp.spec, tests/unit_tests/simpll/CMakeLists.txt
While working on another feature (better development environment), a couple of small improvements for SimpLL unit tests popped up and I realized that they can be useful in general, so posting them straight away.
The list of improvements (see commits for details):
- make vendoring of GoogleTest optional via the `-DVENDOR_GTEST` option of CMake,
- move `runTests` binary back to its default location (i.e. inside the build directory),
- add a new target `ninja test` for conveniently running the unit tests.
=> SimpLL unit test improvements

docker/diffkemp-devel/run-container.py
When running `diffkemp-devel/run-container.py` on Ubuntu it does not recognise command `command` (probably because it is a shell built-in command). This PR fixes it using `shutil.which` instead.
=> Docker-dev: using shutil.which instead of command

diffkemp/simpll/DifferentialFunctionComparator.cpp, tests/regression/test_specs/rhel-80-81-patterns.yaml, tests/unit_tests/simpll/DifferentialFunctionComparatorTest.cpp
After some refactorings, PHI nodes may get reordered. Currently, we do not handle this since PHI nodes are matched in the order in which they appear at the beginning of a basic block.
This simple PR solves the problem by using the following approach:
- During `cmpBasicBlocks`, all comparisons of PHI nodes are skipped.
- When a pair of PHI nodes is used for the first time (by some non-PHI instructions), it is matched.
- After all non-PHI instructions are compared, the matched pairs of PHI nodes are compared.
The PR also fixes a bug in `cmpPHIs` which could cause `cmpPHIs` to compare invalid pairs of PHI-incoming values/blocks. The bug caused the `scnprintf` function to be compared as non-equal between RHEL 8.0 and RHEL 8.1.
=> Match PHI nodes on first use, not based on their order in a basic block

.github/workflows/ci.yml
[viktormalik/rhel-kernel-get](https://github.com/viktormalik/rhel-kernel-get) now has [v0.1](https://github.com/viktormalik/rhel-kernel-get/releases/tag/v0.1) released so let's use that in the CI. The advantage is that we can now develop rhel-kernel-get independently, without accidentally breaking DiffKemp's CI.
=> CI: fix rhel-kernel-get version

.github/workflows/ci.yml, tests/unit_tests/kernel_llvm_source_builder_test.py
When running regression tests on freshly downloaded kernels, it is usually very slow b/c it needs to build the CScope database for each used kernel version.
In CI, this is done for every job in the matrix, despite the fact that building CScope database does not depend on LLVM version.
To speed things up, this PR moves building of the CScope db to the 'cache-kernels' job which downloads and caches the kernels. This is done by running `make cscope` for each downloaded kernel.
Adding some comparison of CI runtimes below.
```
Current master:
- with cached kernels:    30m 56s
- without cached kernels: 43m 43s (11m 18s in cache-kernels)
This PR:
- with cached kernels:    19m 2s
- without cached kernels: 40m 8s (21m 4s in cache-kernels)
```
When considering some measurement errors, we can see …
=> CI speedup: move CScope db build to the cache-kernels job

diffkemp/cli.py, diffkemp/config.py, diffkemp/diffkemp.py, diffkemp/semdiff/caching.py, diffkemp/semdiff/result.py, diffkemp/simpll/Config.cpp, diffkemp/simpll/Config.h, diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/DifferentialFunctionComparator.h, diffkemp/simpll/ModuleComparator.cpp, diffkemp/simpll/ModuleComparator.h, diffkemp/simpll/Output.cpp, diffkemp/simpll/Result.h, diffkemp/simpll/SimpLL.cpp, diffkemp/simpll/library/FFI.cpp, diffkemp/simpll/library/FFI.h, diffkemp/simpll/simpll.py
This PR adds the following statistics:
- number of instructions compared
- number of instructions where 1:1 comparison was used (i.e. semantic preserving pattern was not used)
- number of C code lines analyzed
Tracking the lines analyzed requires a set and the calculations on top of this data-structure resulted in a 10 second (260 -> 270) increase when analyzing the RHEL KABI. This feels quite significant, therefore it has to be explicitly enabled using `--extended-stat` option. The other statistics are just simple counters, therefore, they are included in the base statistics.
Example output comparing RHEL8 kernels:
```
Lines compared:          36537
Instructions compared:   109760
1:1 equal instructions:  107380 (98%)
```
=> Extend statistics

diffkemp/cli.py, diffkemp/config.py, diffkemp/simpll/Config.h, diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/DifferentialFunctionComparator.h, diffkemp/simpll/SimpLL.cpp, diffkemp/simpll/Utils.cpp, diffkemp/simpll/Utils.h, diffkemp/simpll/library/FFI.cpp, diffkemp/simpll/library/FFI.h, tests/unit_tests/simpll/DifferentialFunctionComparatorTest.cpp
This PR adds a pattern that can match reordered commutative binary instructions, such as:
```llvm
;old
%tmp = add i8 0,    i8 1
%res = add i8 %tmp, i8 2
;new
%tmp = add i8 1,    i8 2
%res = add i8 %tmp, i8 0
```
I also fixed two minor issues that would sometimes lead to problems for this pattern and for the upcoming structure refactoring pattern; see commit messages for details.
I assume that this pattern can be safely removed once such refactorings are covered with an SMT solver.
Tests should cover the most basic use cases.
=> Built-in pattern matching reordered commutative operations

diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/DifferentialFunctionComparator.h, diffkemp/simpll/Logger.h, tests/unit_tests/simpll/DifferentialFunctionComparatorTest.cpp
This PR fixes multiple problems with the inverse condition pattern:
1. The pattern could cause a false negative in a code with a combined condition because it always "skiped" a compare instruction with an inverse condition regardless of what the instruction users were. Example which caused false negative:
```c
// old
void f() {                                                               
if (5 == 5 || 10 == 10) {                                            
return true;                                                     
}                                                                    
else return false
}
// new
void f() {                                                               
if (5 != 5 || 10 != 10) {                                            
return true; …
```
=> SimpLL: Inverse condition pattern fixes

diffkemp/simpll/CustomPatternComparator.cpp, diffkemp/simpll/CustomPatternComparator.h, diffkemp/simpll/CustomPatternSet.cpp, diffkemp/simpll/CustomPatternSet.h, diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/DifferentialFunctionComparator.h, diffkemp/simpll/InstPatternComparator.cpp, tests/unit_tests/simpll/DifferentialFunctionComparatorTest.cpp
When matching custom patterns, we should not skip the currently compared instruction, i.e., the one that caused the semantic difference.
Imagine the following situation with two custom patterns:
```llvm
; Pattern 1
!0 = !{ !"pattern-start" }
declare void @diffkemp.new.skippable_1(ptr, i32)
define void @diffkemp.old.pattern_1(i8) {
ret void
}
define void @diffkemp.new.pattern_1(i8) {
%3 = alloca i32
call void @diffkemp.new.skippable_1(ptr %3, i32 4), !diffkemp.pattern !0
ret void
}
```
```llvm
; Pattern 2
!0 = !{ !"pattern-start" }
declare void @diffkemp.new.skippable_2(ptr)
define void @diffkemp.old.pattern_2(i8) {
ret void
}
define void @diffkemp.new.pattern_2(i8) {
%3 = alloca i32
call void @diffkemp.new.skippable_2(ptr %3), !diffkemp.pattern !0
ret void
}
```
The old version of the …
=> Do not skip current instruction when matching custom patterns

.github/workflows/ci.yml, .gitignore, README.md, diffkemp/building/CMakeLists.txt, diffkemp/llvm_ir/kernel_llvm_source_builder.py, flake.lock, flake.nix
This introduces new build and development environments based on [Nix flakes](https://nixos.wiki/wiki/Flakes). In short, Nix is a package manager with focus on replicability and consistency.
This provides several Nix flakes:
- Flake for building DiffKemp with `nix build` or `nix build .#diffkemp-llvm14` for building with a specific LLVM version. This creates a new directory `result/` containing DiffKemp with all dependencies managed by Nix. You can then run it with `result/bin/diffkemp ...`.
- Flake for development environment which can be entered by `nix develop` or `nix develop .#diffkemp-llvm14` (or any other supported LLVM version). This enters a new shell with all dependencies required for building and running DiffKemp, as well as dependencies for building and analysing reasonably …
=> Introduce Nix-based builds and environments

diffkemp/diffkemp.py, diffkemp/snapshot.py
This was possible only for kernel snapshots until now.
It is quite a dirty fix, however. It should probably be updated in the future
in such a way that we copy all modules to the snapshot right away.
=> Enable linking missing source modules for wrapper-built snapshots

diffkemp/cli.py, diffkemp/config.py, diffkemp/simpll/Config.h, diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/DifferentialFunctionComparator.h, diffkemp/simpll/SimpLL.cpp, diffkemp/simpll/Utils.cpp, diffkemp/simpll/Utils.h, diffkemp/simpll/library/FFI.cpp, diffkemp/simpll/library/FFI.h, tests/unit_tests/simpll/DifferentialFunctionComparatorTest.cpp
The pattern works as follows:
- Differing allocas of local memory and stores to such memory are ignored.
- When there is a load from such memory, identifying the replacement works the same as with repetitive loads, i.e., a suitable store has to be found in all backward CFG paths from the load.
Similar to the repetitive loads, this approach is limited by possibly conflicting stores and function calls. Further improvements may be possible using pointer alias analysis (maybe using LLVM's `MemoryDependenceAnalysis` pass?).
In the process of implementing this, I found multiple bugs in the repetitive load skipping implementation; see the first commit.
I'm not really sure about the pattern name; maybe something like `local-memory` would be more suitable?
=> Add a pattern which detects local variable refactorings

diffkemp/simpll/DifferentialFunctionComparator.cpp
Apparently, I made a huge mistake by misinterpreting what `Instruction.isSafeToRemove()` does.
It does not, e.g., return `false` for all `store` instructions.
This is a quick fix to prevent false negatives, I'll think about a more comprehensive solution later.
=> Do not ignore safeToRemove instructions with no users

diffkemp/simpll/Logger.cpp
This PR solves issue #260 .
For methods like cmpValues in Simpll DifferentialFunctionComparator, if the value was llvm::Function, the logger dumped the entire body of the function (which polluted the output), this PR changes it and logs only the function name.
DiffKemp compare output with logger enabled (`-d` set)
- [before the change](https://github.com/viktormalik/diffkemp/files/14478290/old-output.log)
- [after the change](https://github.com/viktormalik/diffkemp/files/14478332/new-output.log)
=> Logger: logging function name instead of its body

diffkemp/simpll/DifferentialFunctionComparator.cpp
If the first equal instruction depends on the relocation, the relocation is not valid, i.e. we return false from findMatchingOpWithOffset. However, in this case we need to keep the Reloc status as None, since otherwise, we may end up with an inconsistent relocation state, e.g. the first call to findMatchingOpWithOffset sets the status to Stored but returns false due to a dependency and then the second call to findMatchingOpWithOffset replaces Reloc.begin. This way, we end up with a relocation with status Stored and Reloc.begin and Reloc.end pointing to different functions.
=> Check relocation validity before marking it Stored

diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/DifferentialFunctionComparator.h, tests/unit_tests/simpll/DifferentialFunctionComparatorTest.cpp
In certain conditions, not checking the type could lead to an assertion failure in cmpOperationsWithOperands. FunctionComparator::cmpOperations checks the types of operands, however if the instructions are an inverse icmp instructions, Diffkemp discards this result. We need to differentiate, whether the non-zero return code from cmpOperations was caused by a difference in types or difference in values before applying the pattern.
The attached test resulted in an assertion failure with current diffkemp version on this line:
https://github.com/diffkemp/diffkemp/blob/789ac18c2c6864b003eac2d77d155cdf87da0a72/diffkemp/simpll/DifferentialFunctionComparator.cpp#L1849-L1850
I thought of two possible solutions to this problem:
1. the one submitted in this PR
2. checking type equality in …
=> Check types when applying inverse cond pattern

diffkemp/diffkemp.py
Temporary directory for cc_wrapper db file was never cleaned up. Added removal of the directory.
=> Build: Cleaning temporary directory

diffkemp/building/cc_wrapper.py, tests/testing_projects/make_based/Makefile, tests/testing_projects/make_based/mod.S, tests/testing_projects/make_based/sub.s, tests/unit_tests/build_test.py
The cc wrapper used to try to compile also assembly, this PR changes it by checking if arguments contain a C source file (`*.c`) if not then it does not tries to compile it. For commands containing linking changes nothing.
To check if I did not break anything I build `musl-1.2.1` -- `musl-1.2.5` and compared snapshots between master and this branch, the snapshots between the branches contain the same files. In musl there were some cases of compilation `*.s` files, before this PR cc_wrapper did try to compile it but because the compilation did not created output file, the file was never added to db file https://github.com/diffkemp/diffkemp/blob/54deef1fbdaabbc6014223a2cf1b4418641b76bb/diffkemp/building/cc_wrapper.py#L210. Now it does not even try to compile it.
I also build …
=> cc wrapper: skipping not C files

diffkemp/building/CMakeLists.txt, diffkemp/building/cc_wrapper.py, diffkemp/cli.py, diffkemp/diffkemp.py, diffkemp/llvm_ir/compiler.py, diffkemp/llvm_ir/kernel_llvm_source_builder.py, diffkemp/llvm_ir/optimiser.py, diffkemp/llvm_ir/single_c_builder.py, diffkemp/llvm_ir/single_llvm_finder.py, flake.nix, tests/unit_tests/build_test.py
DiffKemp contains multiple commands for creating snapshots (`build`, `build-kernel`, `llvm-to-snapshot`), this PR tries to unify  `build` command with `build-kernel` command (as discussed in #287 ). The clang options and LLVM passes are taken from `build-kernel` command, which is taken as the expected default behaviour for `build`.
The `build` command will now by default:
- compile file/project using `-O1 -Xclang -disable-llvm-passes`,
- run selected simplification passes using `opt`.
Using `--clang-drop` does not change the behaviour mentioned above only drops certain flags which are in the Makefile.
Same as before this PR, `--clang_append` can be used to specify other flags which should be added. You can also use it to change the optimization level, but it will still use `-Xclang …
=> Snapshot building unification

.github/workflows/ci.yml
Actions used Node v16 which reached the end of life (11.9.2023) updating to the latest version of actions which uses Node v20.
=> CI: update of actions to latest version

rpm/diffkemp.spec
Several RPM fixes were necessary when building version 0.6.0:
- Replace `pathfix.py ... FILE` by `%py3_shebang_fix FILE` as recommended by a [Fedora change](https://bugzilla.redhat.com/show_bug.cgi?id=1868347).
- Add `BuildRequires: gtest-devel` as we're not vendoring GoogleTest by default.
- Add `Requires: python3-setuptools` to fix #334.
=> RPM fixes for version 0.6.0

diffkemp/semdiff/caching.py, diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/Output.cpp, diffkemp/simpll/Result.h, diffkemp/simpll/SourceCodeUtils.cpp, diffkemp/simpll/SourceCodeUtils.h, tests/unit_tests/caching_test.py, tests/unit_tests/conftest.py, tests/unit_tests/result_test.py
First part of commits from #314 .
This PR adds:
- caching of Syntax difference kind (because there can be multiple kinds of syntax differences - `macro`, `assembly`, `macro-function`, `function-macro`) --  I think it could be useful to have this saved in Python, personally I used this information for visualisation of `function-macro`/`macro-function` differences in the result viewer, but right now I am thinking it is not absolutely necessary because I should be able to deduce this based on names of the differing 'objects', but I am still thinking it could be useful to have it.
- caching of the definition of differing/last macro in Syntax difference -- this is useful for showing code/differences of the macro in the result viewer.
I will reference comments/questions from #314 which are …
=> Caching information about definitions of differing macros

diffkemp/diffkemp.py
Because the function for `view` command is getting long and #314 would add more logic (copying src files also for the new version of the compared project) I thought it could be better if I first refactor the function  - split it into multiple methods of a class. More information is in the commit message.
=> Viewer: Refactoring of view command implementation

diffkemp/cli.py, diffkemp/diffkemp.py
When using `build` command, user can specify file containing names of symbols/functions which he wants to compare.
The command  firstly compiles the project using the CC-wrapper and after that the list of symbols (functions) which should be compared is extracted from the specified file.
So in case the user misstypes name of the file it can takes several minutes than he founds out about the error and he has to run the command again.
A check if the file is valid is added before compiling a project to avoid potentional delays.
=> build-command: Ensure that the symbol list exists

diffkemp/diffkemp.py, view/src/PropTypesValues.js, view/src/components/Callstack.jsx, view/src/components/Code.jsx, view/src/components/DiffViewWrapper.jsx, view/src/components/Difference.jsx, view/src/tests/DiffViewWrapper.test.jsx, view/src/tests/Difference.test.jsx
This PR contains the next set of commits from #314. It prepares the viewer for visualisation of macros, it enables to show code of macros that are located only on one side of a call stack.
The main changes are:
- Previously, we copied only the sources of old version of the compared program,. This PR adds copying of the new project version sources to the folder accessible by the viewer.
- Updates in the `Callstack` component to indicate whether the selected call from the call stack is located in the left, right, or both call stacks. This helps to show the correct version of the code (code for old/new/both versions).
- Enhancements of `DiffViewWrapper` component (component for rendering the code) so it to allow it to show code for only old/new version.
- Because from call stack information …
=> Viewer: preparation of macro visualisation

diffkemp/simpll/ModuleComparator.cpp, diffkemp/simpll/Output.cpp, diffkemp/simpll/Result.h, diffkemp/simpll/SourceCodeUtils.cpp
In PR #333, the `CodeLocation` struct was created to encapsulate information about code location (name of symbol, line, and file on which the symbol appears). This PR refactors  `CallInfo` and `FunctionInfo` structs, which previously contained the `name`, `line`, and `file` fields, to now extend the `CodeLocation` struct.
=> Refactoring: `CallInfo` and `FunctionInfo` to be using `CodeLocation`

.github/workflows/builds.yml, .github/workflows/ci.yml, .github/workflows/code-style.yml, .github/workflows/viewer.yml
So far, we put all CI actions into a single workflow file which is getting quite huge. This separates some jobs into their own workflow files.
=> CI: split workflow files

diffkemp/simpll/ModuleComparator.cpp, diffkemp/simpll/Utils.cpp, tests/regression/test_specs/rhel-81-82.yaml
Run "Global Variable Numbering" pass after inlining functions. This eliminates redundant instructions, for example helps with the following scenario:
Old version:
```llvm
void foo(%0) {
%1 = getelementptr %0, 0, 9
%2 = load %1
call bar(%2)
}
```
New version:
```llvm
void foo(%0) {
%1 = getelementptr %0, 0, 9
call baz(%0)
}
void baz(%10) {
%11 = getelementptr %0, 0, 9
%12 = load %11
call bar(%11)
}
```  
New version of foo after inlining the call to baz:
```llvm
void foo(%0) {
%1 = getelementptr %0, 0, 9
%2 = getelementptr %0, 0, 9
%3 = load %2
call bar(%3)
}
```    
In real-world cases, `%1` and `%2` can be in different basic blocks and the redundancy may be hard to detect. The GVN pass removes the redundant GEP instruction.
Add test which requires the pass to be run, otherwise ends with …
=> SimpLL: run GVN pass after inlining

flake.nix
In order to build some of the newer kernel versions (e.g. 6.9 that we used for experimenting with refactoring commits), libmpc and mpfr are now required, otherwise make prepare fails.
=> Add deps for building upstream kernel to nix

diffkemp/diffkemp.py, docs/usage.md
When searching for usages of a global variable corresponding to a sysctl parameter, there may be multiple functions of the same name (using the sysctl variable) for different arches. In such a case, the snapshot would use the latest one found which may lead to false positives if one snapshot ends up using the implementation from a different architecture than the other.
For building symbol definitions, we always [prefer](https://github.com/diffkemp/diffkemp/blob/master/diffkemp/llvm_ir/kernel_llvm_source_builder.py#L298-L300) definitions for the x86 architecture. This is impossible to do when searching for all functions using a variable, so this disables adding functions from non-x86 architectures to the snapshot.
Also update the documentation to state that we only support x86 in …
=> build-kernel: ignore sysctl usages in non-x86 arch

diffkemp/simpll/DebugInfo.cpp
Add support of `llvm.dbg.assign` instruction [1] which was introduced in LLVM 16 [2]. Now we are skipping this intrinsics instruction which should solve some false positives.
[1] https://llvm.org/docs/SourceLevelDebugging.html#llvm-dbg-assign
[2] https://www.github.com/llvm/llvm-project/commit/33c7ae55e729069be754f56c4d4606cdeddd377b
=> Add llvm.dbg.assign to supported debug intrinsics

flake.nix
We are doing experiments using DiffKemp with security libraries (MbedTLS, Nettle, Sodium, Wolfssl). Some of these libraries need extra dependencies to be able to make snapshots of them. This PR adds the dependencies to nix development shell.
=> Add deps for building of security libs to nix

flake.nix
We use wget to download sources of some projects analysed in experiments.
=> Add wget to Nix flake devShell

view/package-lock.json, view/package.json
The Github-hosted runner (`ubuntu-latest`), which we are using in the CI, recently updated version of Firefox which it contains to version `129.0` [1].
For testing of the Result viewer we are using Cypress besides others. There is a problem because version of Cypress which we are currently using in the CI/workflow does not work in Firefox `129.0` [2]. The problem was fixed in the Cypress v13.0.0+ [3], so this PR updates Cypress to the latest version (13.13.3) to make the Cypress tests work again in the CI.
[1] https://www.github.com/actions/runner-images/commit/eec55f72c9969c43ca5c5a75b5ad8973117c9e89#diff-66aec6097318276b09842a3ba2caf3037afbd8dadca2dfcdf76631100613ea69R171
[2] https://www.github.com/cypress-io/cypress/issues/29713
[3] https://www.github.com/cypress-io/cypress/pull/29720
=> Viewer: Update Cypress version to work in the CI

README.md
Github updated to the latest version of Mermaid (v11.1.0), which caused issues with our diagram in `README.md`.
It looks like Mermaid v11.1.0 no longer supports `\n` for line breaks (probably caused by the introduction of new string syntax [1]). This was fixed by replacing `\n` with `<br/>` tags.
There was also a problem with long labels in the diagram:
- In Firefox, the whole label disappeared [2].
- In Chrome, the label was auto-wrapped, resulting in a poor rendering output.
To fix these problems, the font size of cluster labels was reduced.
Note: The font size is not ideal (too small) but for now I do not have better solution.
[1] https://www.github.com/mermaid-js/mermaid/pull/4271
[2] https://www.github.com/mermaid-js/mermaid/issues/5785
=> Docs: Fix broken diagram in `README.md`

diffkemp/diffkemp.py, diffkemp/llvm_ir/kernel_llvm_source_builder.py
As discribed in issue #313, there can be problem with creating snapshot of kernel if it has missing configuration option. DiffKemp in that case is hanging for input which sets the option. Therefore this commit add check if the kernel is properly configured before creating snapshot
(running `make V=1 --just-print ...` which is used to get command which should be used for compiling of the source file to LLVM IR and which caused the hanging for the config).
The check of kernel config is managed by running `make oldconfig` which prompts for setting of necessary unset options. If we find out the command was prompting for input (contained message 'Restart config' or run too long), we end DiffKemp with apropriate error message.
=> Check kernel config before creating snapshot

.github/workflows/builds.yml
This PR adds to the CI checking that it is possible to use DiffKemp after building it. We have multiple ways how to build DiffKemp:
- nix development build (`nix develop`, `cmake, ninja`, `setuptoolsShellHook`)
- local development build (`cmake`, `ninja`, `pip install -e .`)
- build and installation from sources (`cmake`, `ninja`, `pip install .`, `install ...`).
Each way how to build DiffKemp is done and after that check that the DiffKemp is usable is done by building and comparing `make`-based project (which is already part of the repository and used for unit tests).
The CI should be able to check basic functionality of #344 with some adjustments (removal of `setuptoolsShellHook`, `pip install -e.`, ...).
=> CI: Check DiffKemp builds by running their binary

.github/workflows/builds.yml, .github/workflows/ci.yml, .github/workflows/code-style.yml, diffkemp/simpll/library/FFI.cpp
CI is currently failing due to updates in GitHub runners:
- New clang-format find more styling issues in C++ code. To prevent such failures in future, run clang-format in Nix with a deterministic version (currently 17). Also fix one issue found by clang-format-17.
- Ubuntu 24.04 completely dropped Python 2 so we cannot build the CC-wrapper there anymore. Switch that particular job to Ubuntu 22.04 until we replace RPython by something better.
Also, the `magic-nix-cache-action` is becoming [paid](https://determinate.systems/posts/magic-nix-cache-free-tier-eol/) on Feb 1 so we need to drop it, otherwise our workflows will stop working.
=> Various CI fixes

view/package.json
When building viewer using `npm run build`, the `index.html` expects js and css files to be located in `/static` [1] that makes it impossible to run static server from different than the `build` directory that contains the `index.html`. This commit fixes it by adding homepage that changes the paths to relative -> `./static/...`.
[1] https://create-react-app.dev/docs/deployment/
=> Viewer: use relative paths in the build

.gitignore, diffkemp/cli.py, diffkemp/compare.py, diffkemp/diffkemp.py, diffkemp/utils.py, tests/testing_projects/.gitignore
This PR focuses on refactoring of the compare function, for readability and maintainability purposes.
- Moving it to its own source file `compare.py`
- Splitting it into multiple helper functions
No functional changes are expected as logic was not changed.
While refactoring the compare function, I noticed that some functions, specifically `function_diff` and after refactoring `_print_information`, pass around a lot of variables. I was wondering if it would be beneficial to:
-  create a class, `CompareContext`, to group them together (`mod_first`, `mod_second`, `fun`, `glob_var`, `cache`, ...)
-  maybe, use some of the helper functions, as methods for the class (`_modules_to_cache`, `_set_output_dir`, ...)
This would require further refactoring of not only the `compare.py` file, but also …
=> Compare function refactoring

diffkemp/simpll/DifferentialFunctionComparator.cpp, diffkemp/simpll/Logger.h, diffkemp/simpll/SmtBlockComparator.cpp
Providing more logs for `SmtBlockComparator` (`sequential-alu-ops`) to make it easier to debug problems.
Based on level following things are logged:
- 1+: Start of using `sequential-alu-ops` pattern, success/failure/error of the pattern
- 3+: SMT formula used for instructions comparison
This PR also:
- disables logging when trying to find end of a snippet,
- creates macros for checking what type of debug level is on.
The levels at which the logs are produced are place for discussion.
---
Follows snippets of outputs of the logger run using #411.
```txt
59/84 Test #59: DFCSmtTest.SmtDistributive .............................................***Failed    0.60 sec
Note: Google Test filter = DFCSmtTest.SmtDistributive
[==========] Running 1 test from 1 test suite.
[----------] Global test …
```
=> Logger: Enhance logging for SmtBlockComparator
